// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sepp.Communications.Adapters.Persistence;

#nullable disable

namespace Sepp.Communications.Adapters.Persistence.Migrations
{
    [DbContext(typeof(CommunicationsDbContext))]
    partial class CommunicationsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sepp.BuildingBlocks.Infrastructure.Messaging.InboxMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<string>("Consumer")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("consumer");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.HasKey("MessageId", "Consumer")
                        .HasName("pk_inbox_message");

                    b.ToTable("inbox_message", (string)null);
                });

            modelBuilder.Entity("Sepp.BuildingBlocks.Infrastructure.Messaging.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("event_type");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("topic");

                    b.HasKey("Id")
                        .HasName("pk_outbox_message");

                    b.HasIndex("ProcessedAt")
                        .HasDatabaseName("ix_outbox_message_processed_at")
                        .HasFilter("processed_at IS NULL");

                    b.ToTable("outbox_message", (string)null);
                });

            modelBuilder.Entity("Sepp.Communications.Domain.Messages.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Canal")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("canal");

                    b.Property<string>("CleIdempotence")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("cle_idempotence");

                    b.Property<bool>("ContenuGenerique")
                        .HasColumnType("boolean")
                        .HasColumnName("contenu_generique");

                    b.Property<string>("Corps")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("corps");

                    b.Property<DateTimeOffset>("CreeLe")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cree_le");

                    b.Property<string>("DerniereErreur")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("derniere_erreur");

                    b.Property<Guid>("DestinataireId")
                        .HasColumnType("uuid")
                        .HasColumnName("destinataire_id");

                    b.Property<DateTimeOffset?>("EnvoyeLe")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("envoye_le");

                    b.Property<string>("Langue")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("langue");

                    b.Property<Guid>("ObjetId")
                        .HasColumnType("uuid")
                        .HasColumnName("objet_id");

                    b.Property<string>("ObjetType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("objet_type");

                    b.Property<DateTimeOffset?>("ProchaineTentative")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("prochaine_tentative");

                    b.Property<bool>("Recommande")
                        .HasColumnType("boolean")
                        .HasColumnName("recommande");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("statut");

                    b.Property<string>("Sujet")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("sujet");

                    b.Property<int>("Tentatives")
                        .HasColumnType("integer")
                        .HasColumnName("tentatives");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type");

                    b.Property<string>("TypeDestinataire")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type_destinataire");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("deleted_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTimeOffset>("updated_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("updated_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.Property<int>("version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_message");

                    b.HasIndex("CleIdempotence")
                        .IsUnique()
                        .HasDatabaseName("ix_message_cle_idempotence");

                    b.HasIndex("DestinataireId", "CreeLe")
                        .HasDatabaseName("ix_message_destinataire_id_cree_le");

                    b.HasIndex("ObjetType", "ObjetId")
                        .HasDatabaseName("ix_message_objet_type_objet_id");

                    b.HasIndex("Statut", "ProchaineTentative")
                        .HasDatabaseName("ix_message_statut_prochaine_tentative")
                        .HasFilter("prochaine_tentative IS NOT NULL");

                    b.ToTable("message", (string)null);
                });

            modelBuilder.Entity("Sepp.Communications.Domain.Messages.PreuveEnvoi", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Empreinte")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("empreinte")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("Horodatage")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("horodatage");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reference");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<Guid>("message_id")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<DateTimeOffset>("updated_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("updated_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.Property<int>("version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_preuve_envoi");

                    b.HasIndex("message_id")
                        .HasDatabaseName("ix_preuve_envoi_message_id");

                    b.ToTable("preuve_envoi", (string)null);
                });

            modelBuilder.Entity("Sepp.Communications.Domain.Messages.PreuveEnvoi", b =>
                {
                    b.HasOne("Sepp.Communications.Domain.Messages.Message", null)
                        .WithMany("Preuves")
                        .HasForeignKey("message_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_preuve_envoi_message_message_id");
                });

            modelBuilder.Entity("Sepp.Communications.Domain.Messages.Message", b =>
                {
                    b.Navigation("Preuves");
                });
#pragma warning restore 612, 618
        }
    }
}
