<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="Shouldly" />
    <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" />

  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Sepp.Affilies.Domain\Sepp.Affilies.Domain.csproj" />
  </ItemGroup>
</Project>
