<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AnalysisLevel>latest-recommended</AnalysisLevel>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <InvariantGlobalization>false</InvariantGlobalization>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <Company>SEPP</Company>
    <Product>Veilla</Product>
    <!-- CA1062/CA1848/CA2007 : trop bruyantes pour du code applicatif ASP.NET Core -->
    <NoWarn>$(NoWarn);CA1062;CA1848;CA2007;CA1716;CA1711;CA1515;CA1034;CA1724</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="$(MSBuildProjectName.EndsWith('Tests'))">
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <OutputType>Exe</OutputType>
    <NoWarn>$(NoWarn);CA1707;CA1307;CA1305;CA1861;CA2201</NoWarn>
  </PropertyGroup>
</Project>
