<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <AssemblyName>Sepp.Personnes</AssemblyName>
    <RootNamespace>Sepp.Personnes.Infrastructure</RootNamespace>
    <UserSecretsId>sepp-personnes</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" PrivateAssets="all" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Sepp.Personnes.Adapters\Sepp.Personnes.Adapters.csproj" />
  </ItemGroup>
</Project>
