<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <AssemblyName>Sepp.Planification</AssemblyName>
    <RootNamespace>Sepp.Planification.Infrastructure</RootNamespace>
    <UserSecretsId>sepp-planification</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" PrivateAssets="all" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Sepp.Planification.Adapters\Sepp.Planification.Adapters.csproj" />
  </ItemGroup>
</Project>
