// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sepp.PostesRisques.Adapters.Persistence;

#nullable disable

namespace Sepp.PostesRisques.Adapters.Persistence.Migrations
{
    [DbContext(typeof(PostesRisquesDbContext))]
    [Migration("20260928115130_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sepp.BuildingBlocks.Infrastructure.Messaging.InboxMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<string>("Consumer")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("consumer");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.HasKey("MessageId", "Consumer")
                        .HasName("pk_inbox_message");

                    b.ToTable("inbox_message", (string)null);
                });

            modelBuilder.Entity("Sepp.BuildingBlocks.Infrastructure.Messaging.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("event_type");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("topic");

                    b.HasKey("Id")
                        .HasName("pk_outbox_message");

                    b.HasIndex("ProcessedAt")
                        .HasDatabaseName("ix_outbox_message_processed_at")
                        .HasFilter("processed_at IS NULL");

                    b.ToTable("outbox_message", (string)null);
                });

            modelBuilder.Entity("Sepp.PostesRisques.Domain.Listes.LigneListeNominative", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.PrimitiveCollection<string[]>("CodesRisques")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("codes_risques");

                    b.Property<DateOnly?>("DateDerniereEvaluation")
                        .HasColumnType("date")
                        .HasColumnName("date_derniere_evaluation");

                    b.Property<string>("Origine")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("origine");

                    b.Property<Guid>("PersonneId")
                        .HasColumnType("uuid")
                        .HasColumnName("personne_id");

                    b.Property<Guid>("PosteId")
                        .HasColumnType("uuid")
                        .HasColumnName("poste_id");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<Guid>("liste_nominative_id")
                        .HasColumnType("uuid")
                        .HasColumnName("liste_nominative_id");

                    b.Property<DateTimeOffset>("updated_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("updated_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.Property<int>("version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_ligne_liste_nominative");

                    b.HasIndex("PersonneId")
                        .HasDatabaseName("ix_ligne_liste_nominative_personne_id");

                    b.HasIndex("liste_nominative_id")
                        .HasDatabaseName("ix_ligne_liste_nominative_liste_nominative_id");

                    b.ToTable("ligne_liste_nominative", (string)null);
                });

            modelBuilder.Entity("Sepp.PostesRisques.Domain.Listes.LignePropositionListe", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("PersonneId")
                        .HasColumnType("uuid")
                        .HasColumnName("personne_id");

                    b.Property<Guid>("PosteId")
                        .HasColumnType("uuid")
                        .HasColumnName("poste_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<Guid>("proposition_liste_nominative_id")
                        .HasColumnType("uuid")
                        .HasColumnName("proposition_liste_nominative_id");

                    b.Property<DateTimeOffset>("updated_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("updated_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.Property<int>("version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_ligne_proposition_liste");

                    b.HasIndex("proposition_liste_nominative_id")
                        .HasDatabaseName("ix_ligne_proposition_liste_proposition_liste_nominative_id");

                    b.ToTable("ligne_proposition_liste", (string)null);
                });

            modelBuilder.Entity("Sepp.PostesRisques.Domain.Listes.ListeNominative", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AffilieId")
                        .HasColumnType("uuid")
                        .HasColumnName("affilie_id");

                    b.Property<DateOnly>("ConserverJusquAu")
                        .HasColumnType("date")
                        .HasColumnName("conserver_jusqu_au");

                    b.Property<DateTimeOffset>("DateGeneration")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_generation");

                    b.Property<DateOnly>("DateReference")
                        .HasColumnType("date")
                        .HasColumnName("date_reference");

                    b.Property<Guid?>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<string>("GenereePar")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("generee_par");

                    b.Property<Guid?>("PropositionId")
                        .HasColumnType("uuid")
                        .HasColumnName("proposition_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("type");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("deleted_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTimeOffset>("updated_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("updated_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.Property<int>("version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_liste_nominative");

                    b.HasIndex("AffilieId", "Type", "Version")
                        .IsUnique()
                        .HasDatabaseName("ix_liste_nominative_affilie_id_type_version");

                    b.ToTable("liste_nominative", null, t =>
                        {
                            t.Property("version")
                                .HasColumnName("version1");
                        });
                });

            modelBuilder.Entity("Sepp.PostesRisques.Domain.Listes.PropositionListeNominative", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AffilieId")
                        .HasColumnType("uuid")
                        .HasColumnName("affilie_id");

                    b.Property<DateTimeOffset?>("DateDecision")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_decision");

                    b.Property<DateTimeOffset>("DateProposition")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_proposition");

                    b.Property<string>("DecidePar")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("decide_par");

                    b.Property<Guid>("ListeNominativeId")
                        .HasColumnType("uuid")
                        .HasColumnName("liste_nominative_id");

                    b.Property<Guid?>("ListeResultanteId")
                        .HasColumnType("uuid")
                        .HasColumnName("liste_resultante_id");

                    b.Property<string>("Motif")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("motif");

                    b.Property<string>("MotifRefus")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("motif_refus");

                    b.Property<string>("Origine")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("origine");

                    b.Property<string>("ProposeePar")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("proposee_par");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("statut");

                    b.Property<string>("TypeListe")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("type_liste");

                    b.Property<int>("VersionListe")
                        .HasColumnType("integer")
                        .HasColumnName("version_liste");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("deleted_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTimeOffset>("updated_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("updated_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.Property<int>("version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_proposition_liste_nominative");

                    b.HasIndex("ListeNominativeId")
                        .HasDatabaseName("ix_proposition_liste_nominative_liste_nominative_id");

                    b.HasIndex("AffilieId", "Statut")
                        .HasDatabaseName("ix_proposition_liste_nominative_affilie_id_statut");

                    b.ToTable("proposition_liste_nominative", (string)null);
                });

            modelBuilder.Entity("Sepp.PostesRisques.Domain.Postes.LignePropositionPosteRisque", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("NiveauExposition")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("niveau_exposition");

                    b.Property<string>("RisqueCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("risque_code");

                    b.Property<Guid>("RisqueId")
                        .HasColumnType("uuid")
                        .HasColumnName("risque_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<Guid>("proposition_poste_risque_id")
                        .HasColumnType("uuid")
                        .HasColumnName("proposition_poste_risque_id");

                    b.Property<DateTimeOffset>("updated_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("updated_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.Property<int>("version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_ligne_proposition_poste_risque");

                    b.HasIndex("RisqueId")
                        .HasDatabaseName("ix_ligne_proposition_poste_risque_risque_id");

                    b.HasIndex("proposition_poste_risque_id")
                        .HasDatabaseName("ix_ligne_proposition_poste_risque_proposition_poste_risque_id");

                    b.ToTable("ligne_proposition_poste_risque", (string)null);
                });

            modelBuilder.Entity("Sepp.PostesRisques.Domain.Postes.Poste", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AffilieId")
                        .HasColumnType("uuid")
                        .HasColumnName("affilie_id");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("Intitule")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("intitule");

                    b.Property<string>("MetierTypeCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("metier_type_code");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("statut");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("deleted_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTimeOffset>("updated_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("updated_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.Property<int>("version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_poste");

                    b.HasIndex("AffilieId")
                        .HasDatabaseName("ix_poste_affilie_id");

                    b.ToTable("poste", (string)null);
                });

            modelBuilder.Entity("Sepp.PostesRisques.Domain.Postes.PosteRisque", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("DateAvisCppt")
                        .HasColumnType("date")
                        .HasColumnName("date_avis_cppt");

                    b.Property<Guid>("DocumentAvisCpptId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_avis_cppt_id");

                    b.Property<string>("NiveauExposition")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("niveau_exposition");

                    b.Property<Guid>("PropositionId")
                        .HasColumnType("uuid")
                        .HasColumnName("proposition_id");

                    b.Property<string>("RisqueCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("risque_code");

                    b.Property<Guid>("RisqueId")
                        .HasColumnType("uuid")
                        .HasColumnName("risque_id");

                    b.Property<string>("ValideParCpmtId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("valide_par_cpmt_id");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<Guid>("poste_id")
                        .HasColumnType("uuid")
                        .HasColumnName("poste_id");

                    b.Property<DateTimeOffset>("updated_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("updated_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.Property<int>("version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Validite", "Sepp.PostesRisques.Domain.Postes.PosteRisque.Validite#Validity", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateOnly>("ValidFrom")
                                .HasColumnType("date")
                                .HasColumnName("valid_from");

                            b1.Property<DateOnly?>("ValidTo")
                                .HasColumnType("date")
                                .HasColumnName("valid_to");
                        });

                    b.HasKey("Id")
                        .HasName("pk_poste_risque");

                    b.HasIndex("RisqueId")
                        .HasDatabaseName("ix_poste_risque_risque_id");

                    b.HasIndex("poste_id", "RisqueId")
                        .HasDatabaseName("ix_poste_risque_poste_id_risque_id");

                    b.ToTable("poste_risque", (string)null);
                });

            modelBuilder.Entity("Sepp.PostesRisques.Domain.Postes.PropositionPosteRisque", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AffilieId")
                        .HasColumnType("uuid")
                        .HasColumnName("affilie_id");

                    b.Property<DateOnly?>("DateAvisCppt")
                        .HasColumnType("date")
                        .HasColumnName("date_avis_cppt");

                    b.Property<DateTimeOffset?>("DateDecision")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_decision");

                    b.Property<DateTimeOffset>("DateProposition")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_proposition");

                    b.Property<string>("DecidePar")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("decide_par");

                    b.Property<Guid?>("DocumentAvisCpptId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_avis_cppt_id");

                    b.Property<string>("Motif")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("motif");

                    b.Property<string>("MotifRefus")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("motif_refus");

                    b.Property<string>("Origine")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("origine");

                    b.Property<Guid>("PosteId")
                        .HasColumnType("uuid")
                        .HasColumnName("poste_id");

                    b.Property<string>("ProposeePar")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("proposee_par");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("statut");

                    b.Property<DateOnly>("ValideDu")
                        .HasColumnType("date")
                        .HasColumnName("valide_du");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("deleted_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTimeOffset>("updated_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("updated_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.Property<int>("version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_proposition_poste_risque");

                    b.HasIndex("PosteId")
                        .HasDatabaseName("ix_proposition_poste_risque_poste_id");

                    b.HasIndex("AffilieId", "Statut")
                        .HasDatabaseName("ix_proposition_poste_risque_affilie_id_statut");

                    b.ToTable("proposition_poste_risque", (string)null);
                });

            modelBuilder.Entity("Sepp.PostesRisques.Domain.Projections.AffectationPoste", b =>
                {
                    b.Property<Guid>("AffectationId")
                        .HasColumnType("uuid")
                        .HasColumnName("affectation_id");

                    b.Property<DateOnly>("DateDebut")
                        .HasColumnType("date")
                        .HasColumnName("date_debut");

                    b.Property<DateOnly?>("DateFin")
                        .HasColumnType("date")
                        .HasColumnName("date_fin");

                    b.Property<DateTimeOffset>("EvenementDu")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("evenement_du");

                    b.Property<Guid>("PersonneId")
                        .HasColumnType("uuid")
                        .HasColumnName("personne_id");

                    b.Property<Guid>("PosteId")
                        .HasColumnType("uuid")
                        .HasColumnName("poste_id");

                    b.HasKey("AffectationId")
                        .HasName("pk_affectation_poste");

                    b.HasIndex("PersonneId")
                        .HasDatabaseName("ix_affectation_poste_personne_id");

                    b.HasIndex("PosteId")
                        .HasDatabaseName("ix_affectation_poste_poste_id");

                    b.ToTable("affectation_poste", (string)null);
                });

            modelBuilder.Entity("Sepp.PostesRisques.Domain.Projections.ExamenRealise", b =>
                {
                    b.Property<Guid>("ExamenId")
                        .HasColumnType("uuid")
                        .HasColumnName("examen_id");

                    b.Property<Guid>("AffilieId")
                        .HasColumnType("uuid")
                        .HasColumnName("affilie_id");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<Guid>("PersonneId")
                        .HasColumnType("uuid")
                        .HasColumnName("personne_id");

                    b.Property<string>("TypeExamen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("type_examen");

                    b.HasKey("ExamenId")
                        .HasName("pk_examen_realise");

                    b.HasIndex("AffilieId", "PersonneId", "Date")
                        .HasDatabaseName("ix_examen_realise_affilie_id_personne_id_date");

                    b.ToTable("examen_realise", (string)null);
                });

            modelBuilder.Entity("Sepp.PostesRisques.Domain.Projections.ParametreLegalLocal", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<DateOnly>("ValideDu")
                        .HasColumnType("date")
                        .HasColumnName("valide_du");

                    b.Property<string>("Unite")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("unite");

                    b.Property<decimal>("Valeur")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("valeur");

                    b.Property<DateOnly?>("ValideJusquAu")
                        .HasColumnType("date")
                        .HasColumnName("valide_jusqu_au");

                    b.HasKey("Code", "ValideDu")
                        .HasName("pk_parametre_legal_local");

                    b.ToTable("parametre_legal_local", (string)null);
                });

            modelBuilder.Entity("Sepp.PostesRisques.Domain.Risques.RegleSurveillance", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.PrimitiveCollection<string[]>("ActesSupplementaires")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("actes_supplementaires");

                    b.Property<int?>("FrequenceMois")
                        .HasColumnType("integer")
                        .HasColumnName("frequence_mois");

                    b.Property<bool>("SurveillanceProlongee")
                        .HasColumnType("boolean")
                        .HasColumnName("surveillance_prolongee");

                    b.Property<string>("TypeSurveillance")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("type_surveillance");

                    b.PrimitiveCollection<string[]>("Vaccins")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("vaccins");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<Guid>("risque_id")
                        .HasColumnType("uuid")
                        .HasColumnName("risque_id");

                    b.Property<DateTimeOffset>("updated_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("updated_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.Property<int>("version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Validite", "Sepp.PostesRisques.Domain.Risques.RegleSurveillance.Validite#Validity", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateOnly>("ValidFrom")
                                .HasColumnType("date")
                                .HasColumnName("valid_from");

                            b1.Property<DateOnly?>("ValidTo")
                                .HasColumnType("date")
                                .HasColumnName("valid_to");
                        });

                    b.HasKey("Id")
                        .HasName("pk_regle_surveillance");

                    b.HasIndex("risque_id", "Version")
                        .IsUnique()
                        .HasDatabaseName("ix_regle_surveillance_risque_id_version");

                    b.ToTable("regle_surveillance", null, t =>
                        {
                            t.Property("version")
                                .HasColumnName("version1");
                        });
                });

            modelBuilder.Entity("Sepp.PostesRisques.Domain.Risques.Risque", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Categorie")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("categorie");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<string>("ReferenceLegale")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reference_legale");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("deleted_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTimeOffset>("updated_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("updated_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.Property<int>("version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Libelle", "Sepp.PostesRisques.Domain.Risques.Risque.Libelle#LocalizedLabel", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("De")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("libelle_de");

                            b1.Property<string>("En")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("libelle_en");

                            b1.Property<string>("Fr")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("libelle_fr");

                            b1.Property<string>("Nl")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("libelle_nl");
                        });

                    b.HasKey("Id")
                        .HasName("pk_risque");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_risque_code");

                    b.ToTable("risque", (string)null);
                });

            modelBuilder.Entity("Sepp.PostesRisques.Domain.Surcharges.SurchargeFrequence", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AffilieId")
                        .HasColumnType("uuid")
                        .HasColumnName("affilie_id");

                    b.Property<Guid>("CibleId")
                        .HasColumnType("uuid")
                        .HasColumnName("cible_id");

                    b.Property<string>("CibleType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("cible_type");

                    b.Property<string>("CpmtId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cpmt_id");

                    b.Property<int>("FrequenceMois")
                        .HasColumnType("integer")
                        .HasColumnName("frequence_mois");

                    b.Property<string>("Motif")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("motif");

                    b.Property<string>("RisqueCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("risque_code");

                    b.Property<Guid>("RisqueId")
                        .HasColumnType("uuid")
                        .HasColumnName("risque_id");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("deleted_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTimeOffset>("updated_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("updated_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.Property<int>("version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Validite", "Sepp.PostesRisques.Domain.Surcharges.SurchargeFrequence.Validite#Validity", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateOnly>("ValidFrom")
                                .HasColumnType("date")
                                .HasColumnName("valid_from");

                            b1.Property<DateOnly?>("ValidTo")
                                .HasColumnType("date")
                                .HasColumnName("valid_to");
                        });

                    b.HasKey("Id")
                        .HasName("pk_surcharge_frequence");

                    b.HasIndex("RisqueId")
                        .HasDatabaseName("ix_surcharge_frequence_risque_id");

                    b.HasIndex("AffilieId", "CibleType", "CibleId")
                        .HasDatabaseName("ix_surcharge_frequence_affilie_id_cible_type_cible_id");

                    b.ToTable("surcharge_frequence", (string)null);
                });

            modelBuilder.Entity("Sepp.PostesRisques.Domain.Listes.LigneListeNominative", b =>
                {
                    b.HasOne("Sepp.PostesRisques.Domain.Listes.ListeNominative", null)
                        .WithMany("Lignes")
                        .HasForeignKey("liste_nominative_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ligne_liste_nominative_liste_nominative_liste_nominative_id");
                });

            modelBuilder.Entity("Sepp.PostesRisques.Domain.Listes.LignePropositionListe", b =>
                {
                    b.HasOne("Sepp.PostesRisques.Domain.Listes.PropositionListeNominative", null)
                        .WithMany("Lignes")
                        .HasForeignKey("proposition_liste_nominative_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ligne_proposition_liste_proposition_liste_nominative_propos");
                });

            modelBuilder.Entity("Sepp.PostesRisques.Domain.Listes.PropositionListeNominative", b =>
                {
                    b.HasOne("Sepp.PostesRisques.Domain.Listes.ListeNominative", null)
                        .WithMany()
                        .HasForeignKey("ListeNominativeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_proposition_liste_nominative_liste_nominative_liste_nominat");
                });

            modelBuilder.Entity("Sepp.PostesRisques.Domain.Postes.LignePropositionPosteRisque", b =>
                {
                    b.HasOne("Sepp.PostesRisques.Domain.Risques.Risque", null)
                        .WithMany()
                        .HasForeignKey("RisqueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ligne_proposition_poste_risque_risque_risque_id");

                    b.HasOne("Sepp.PostesRisques.Domain.Postes.PropositionPosteRisque", null)
                        .WithMany("Lignes")
                        .HasForeignKey("proposition_poste_risque_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ligne_proposition_poste_risque_proposition_poste_risque_pro");
                });

            modelBuilder.Entity("Sepp.PostesRisques.Domain.Postes.PosteRisque", b =>
                {
                    b.HasOne("Sepp.PostesRisques.Domain.Risques.Risque", null)
                        .WithMany()
                        .HasForeignKey("RisqueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_poste_risque_risque_risque_id");

                    b.HasOne("Sepp.PostesRisques.Domain.Postes.Poste", null)
                        .WithMany("Risques")
                        .HasForeignKey("poste_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_poste_risque_poste_poste_id");
                });

            modelBuilder.Entity("Sepp.PostesRisques.Domain.Postes.PropositionPosteRisque", b =>
                {
                    b.HasOne("Sepp.PostesRisques.Domain.Postes.Poste", null)
                        .WithMany()
                        .HasForeignKey("PosteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_proposition_poste_risque_poste_poste_id");
                });

            modelBuilder.Entity("Sepp.PostesRisques.Domain.Risques.RegleSurveillance", b =>
                {
                    b.HasOne("Sepp.PostesRisques.Domain.Risques.Risque", null)
                        .WithMany("Regles")
                        .HasForeignKey("risque_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_regle_surveillance_risque_risque_id");
                });

            modelBuilder.Entity("Sepp.PostesRisques.Domain.Surcharges.SurchargeFrequence", b =>
                {
                    b.HasOne("Sepp.PostesRisques.Domain.Risques.Risque", null)
                        .WithMany()
                        .HasForeignKey("RisqueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_surcharge_frequence_risque_risque_id");
                });

            modelBuilder.Entity("Sepp.PostesRisques.Domain.Listes.ListeNominative", b =>
                {
                    b.Navigation("Lignes");
                });

            modelBuilder.Entity("Sepp.PostesRisques.Domain.Listes.PropositionListeNominative", b =>
                {
                    b.Navigation("Lignes");
                });

            modelBuilder.Entity("Sepp.PostesRisques.Domain.Postes.Poste", b =>
                {
                    b.Navigation("Risques");
                });

            modelBuilder.Entity("Sepp.PostesRisques.Domain.Postes.PropositionPosteRisque", b =>
                {
                    b.Navigation("Lignes");
                });

            modelBuilder.Entity("Sepp.PostesRisques.Domain.Risques.Risque", b =>
                {
                    b.Navigation("Regles");
                });
#pragma warning restore 612, 618
        }
    }
}
