// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sepp.Personnes.Adapters.Persistence;

#nullable disable

namespace Sepp.Personnes.Adapters.Persistence.Migrations
{
    [DbContext(typeof(PersonnesDbContext))]
    [Migration("20261009102342_MutationsRegistreNational")]
    partial class MutationsRegistreNational
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sepp.BuildingBlocks.Infrastructure.Messaging.InboxMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<string>("Consumer")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("consumer");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.HasKey("MessageId", "Consumer")
                        .HasName("pk_inbox_message");

                    b.ToTable("inbox_message", (string)null);
                });

            modelBuilder.Entity("Sepp.BuildingBlocks.Infrastructure.Messaging.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("event_type");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("topic");

                    b.HasKey("Id")
                        .HasName("pk_outbox_message");

                    b.HasIndex("ProcessedAt")
                        .HasDatabaseName("ix_outbox_message_processed_at")
                        .HasFilter("processed_at IS NULL");

                    b.ToTable("outbox_message", (string)null);
                });

            modelBuilder.Entity("Sepp.Personnes.Domain.Personnes.Affectation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("PosteId")
                        .HasColumnType("uuid")
                        .HasColumnName("poste_id");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<Guid>("occupation_id")
                        .HasColumnType("uuid")
                        .HasColumnName("occupation_id");

                    b.Property<DateTimeOffset>("updated_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("updated_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.Property<int>("version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Validite", "Sepp.Personnes.Domain.Personnes.Affectation.Validite#Validity", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateOnly>("ValidFrom")
                                .HasColumnType("date")
                                .HasColumnName("valid_from");

                            b1.Property<DateOnly?>("ValidTo")
                                .HasColumnType("date")
                                .HasColumnName("valid_to");
                        });

                    b.HasKey("Id")
                        .HasName("pk_affectation");

                    b.HasIndex("PosteId")
                        .HasDatabaseName("ix_affectation_poste_id");

                    b.HasIndex("occupation_id")
                        .HasDatabaseName("ix_affectation_occupation_id");

                    b.ToTable("affectation", (string)null);
                });

            modelBuilder.Entity("Sepp.Personnes.Domain.Personnes.EtatParticulier", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AffilieDeclarantId")
                        .HasColumnType("uuid")
                        .HasColumnName("affilie_declarant_id");

                    b.Property<DateOnly>("DateDebut")
                        .HasColumnType("date")
                        .HasColumnName("date_debut");

                    b.Property<DateOnly?>("DateFin")
                        .HasColumnType("date")
                        .HasColumnName("date_fin");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("type_chiffre");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<Guid>("personne_id")
                        .HasColumnType("uuid")
                        .HasColumnName("personne_id");

                    b.Property<DateTimeOffset>("updated_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("updated_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.Property<int>("version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_etat_particulier");

                    b.HasIndex("personne_id")
                        .HasDatabaseName("ix_etat_particulier_personne_id");

                    b.ToTable("etat_particulier", (string)null);
                });

            modelBuilder.Entity("Sepp.Personnes.Domain.Personnes.MutationRegistreNational", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Apres")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("apres_chiffre");

                    b.Property<string>("Avant")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("avant_chiffre");

                    b.Property<DateOnly>("DateEffet")
                        .HasColumnType("date")
                        .HasColumnName("date_effet");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reference");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<Guid>("personne_id")
                        .HasColumnType("uuid")
                        .HasColumnName("personne_id");

                    b.Property<DateTimeOffset>("updated_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("updated_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.Property<int>("version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_mutation_registre_national");

                    b.HasIndex("Reference")
                        .IsUnique()
                        .HasDatabaseName("ix_mutation_registre_national_reference");

                    b.HasIndex("personne_id")
                        .HasDatabaseName("ix_mutation_registre_national_personne_id");

                    b.ToTable("mutation_registre_national", (string)null);
                });

            modelBuilder.Entity("Sepp.Personnes.Domain.Personnes.Occupation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AffilieId")
                        .HasColumnType("uuid")
                        .HasColumnName("affilie_id");

                    b.Property<Guid?>("AffilieUtilisateurId")
                        .HasColumnType("uuid")
                        .HasColumnName("affilie_utilisateur_id");

                    b.Property<DateOnly>("DateDebut")
                        .HasColumnType("date")
                        .HasColumnName("date_debut");

                    b.Property<DateOnly?>("DateFin")
                        .HasColumnType("date")
                        .HasColumnName("date_fin");

                    b.Property<string>("ReferenceDimona")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("reference_dimona");

                    b.Property<string>("TypeContrat")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type_contrat");

                    b.Property<string>("TypeTravailleur")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type_travailleur");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<Guid>("personne_id")
                        .HasColumnType("uuid")
                        .HasColumnName("personne_id");

                    b.Property<DateTimeOffset>("updated_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("updated_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.Property<int>("version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_occupation");

                    b.HasIndex("AffilieId")
                        .HasDatabaseName("ix_occupation_affilie_id");

                    b.HasIndex("AffilieUtilisateurId")
                        .HasDatabaseName("ix_occupation_affilie_utilisateur_id");

                    b.HasIndex("ReferenceDimona")
                        .IsUnique()
                        .HasDatabaseName("ix_occupation_reference_dimona")
                        .HasFilter("reference_dimona IS NOT NULL");

                    b.HasIndex("personne_id")
                        .HasDatabaseName("ix_occupation_personne_id");

                    b.ToTable("occupation", (string)null);
                });

            modelBuilder.Entity("Sepp.Personnes.Domain.Personnes.Personne", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CanalPrefere")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("canal_prefere");

                    b.Property<DateOnly?>("DateDeces")
                        .HasColumnType("date")
                        .HasColumnName("date_deces");

                    b.Property<DateOnly>("DateNaissance")
                        .HasColumnType("date")
                        .HasColumnName("date_naissance");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<string>("Langue")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("langue");

                    b.Property<string>("Niss")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("niss_chiffre");

                    b.Property<string>("NissHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("niss_hash");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nom");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("prenom");

                    b.Property<string>("Sexe")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("sexe");

                    b.Property<string>("Telephone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("telephone");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("deleted_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTimeOffset>("updated_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("updated_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.Property<int>("version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Adresse", "Sepp.Personnes.Domain.Personnes.Personne.Adresse#Adresse", b1 =>
                        {
                            b1.Property<string>("Boite")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("adresse_boite");

                            b1.Property<string>("CodePostal")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("adresse_code_postal");

                            b1.Property<string>("Localite")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("adresse_localite");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("adresse_numero");

                            b1.Property<string>("Pays")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)")
                                .HasColumnName("adresse_pays");

                            b1.Property<string>("Rue")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("adresse_rue");
                        });

                    b.HasKey("Id")
                        .HasName("pk_personne");

                    b.HasIndex("NissHash")
                        .IsUnique()
                        .HasDatabaseName("ix_personne_niss_hash");

                    b.ToTable("personne", (string)null);
                });

            modelBuilder.Entity("Sepp.Personnes.Domain.Personnes.Affectation", b =>
                {
                    b.HasOne("Sepp.Personnes.Domain.Personnes.Occupation", null)
                        .WithMany("Affectations")
                        .HasForeignKey("occupation_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_affectation_occupation_occupation_id");
                });

            modelBuilder.Entity("Sepp.Personnes.Domain.Personnes.EtatParticulier", b =>
                {
                    b.HasOne("Sepp.Personnes.Domain.Personnes.Personne", null)
                        .WithMany("EtatsParticuliers")
                        .HasForeignKey("personne_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_etat_particulier_personne_personne_id");
                });

            modelBuilder.Entity("Sepp.Personnes.Domain.Personnes.MutationRegistreNational", b =>
                {
                    b.HasOne("Sepp.Personnes.Domain.Personnes.Personne", null)
                        .WithMany("Mutations")
                        .HasForeignKey("personne_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_mutation_registre_national_personne_personne_id");
                });

            modelBuilder.Entity("Sepp.Personnes.Domain.Personnes.Occupation", b =>
                {
                    b.HasOne("Sepp.Personnes.Domain.Personnes.Personne", null)
                        .WithMany("Occupations")
                        .HasForeignKey("personne_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_occupation_personne_personne_id");
                });

            modelBuilder.Entity("Sepp.Personnes.Domain.Personnes.Occupation", b =>
                {
                    b.Navigation("Affectations");
                });

            modelBuilder.Entity("Sepp.Personnes.Domain.Personnes.Personne", b =>
                {
                    b.Navigation("EtatsParticuliers");

                    b.Navigation("Mutations");

                    b.Navigation("Occupations");
                });
#pragma warning restore 612, 618
        }
    }
}
