// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sepp.SurveillanceMedicale.Adapters.Persistence;

#nullable disable

namespace Sepp.SurveillanceMedicale.Adapters.Persistence.Migrations
{
    [DbContext(typeof(SurveillanceMedicaleDbContext))]
    [Migration("20261005134434_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sepp.BuildingBlocks.Infrastructure.Messaging.InboxMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<string>("Consumer")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("consumer");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.HasKey("MessageId", "Consumer")
                        .HasName("pk_inbox_message");

                    b.ToTable("inbox_message", (string)null);
                });

            modelBuilder.Entity("Sepp.BuildingBlocks.Infrastructure.Messaging.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("event_type");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("topic");

                    b.HasKey("Id")
                        .HasName("pk_outbox_message");

                    b.HasIndex("ProcessedAt")
                        .HasDatabaseName("ix_outbox_message_processed_at")
                        .HasFilter("processed_at IS NULL");

                    b.ToTable("outbox_message", (string)null);
                });

            modelBuilder.Entity("Sepp.SurveillanceMedicale.Domain.Conservation.DureeConservationExposition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Annees")
                        .HasColumnType("integer")
                        .HasColumnName("annees");

                    b.Property<string>("BaseLegale")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("base_legale");

                    b.Property<string>("CodeAgent")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("code_agent");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("deleted_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTimeOffset>("updated_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("updated_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.Property<int>("version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_duree_conservation_exposition");

                    b.HasIndex("CodeAgent")
                        .IsUnique()
                        .HasDatabaseName("ix_duree_conservation_exposition_code_agent");

                    b.ToTable("duree_conservation_exposition", (string)null);
                });

            modelBuilder.Entity("Sepp.SurveillanceMedicale.Domain.Conservation.PreuveDestruction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("DatePurgePrevue")
                        .HasColumnType("date")
                        .HasColumnName("date_purge_prevue");

                    b.Property<DateTimeOffset>("DetruitLe")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("detruit_le");

                    b.Property<Guid>("DossierId")
                        .HasColumnType("uuid")
                        .HasColumnName("dossier_id");

                    b.Property<string>("Empreinte")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("empreinte");

                    b.Property<string>("MotifValidation")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("motif_validation");

                    b.Property<int>("NombreElements")
                        .HasColumnType("integer")
                        .HasColumnName("nombre_elements");

                    b.Property<Guid>("PersonneId")
                        .HasColumnType("uuid")
                        .HasColumnName("personne_id");

                    b.Property<string>("ValideePar")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("validee_par");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("deleted_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTimeOffset>("updated_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("updated_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.Property<int>("version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_preuve_destruction");

                    b.HasIndex("DossierId")
                        .IsUnique()
                        .HasDatabaseName("ix_preuve_destruction_dossier_id");

                    b.ToTable("preuve_destruction", (string)null);
                });

            modelBuilder.Entity("Sepp.SurveillanceMedicale.Domain.Decisions.Decision", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AffilieId")
                        .HasColumnType("uuid")
                        .HasColumnName("affilie_id");

                    b.Property<string>("AuteurId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("auteur_id");

                    b.Property<string>("Categorie")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("categorie");

                    b.Property<DateOnly>("DateExamen")
                        .HasColumnType("date")
                        .HasColumnName("date_examen");

                    b.Property<Guid?>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<Guid>("DossierId")
                        .HasColumnType("uuid")
                        .HasColumnName("dossier_id");

                    b.Property<Guid>("ExamenId")
                        .HasColumnType("uuid")
                        .HasColumnName("examen_id");

                    b.Property<string>("Justification")
                        .HasMaxLength(100000)
                        .HasColumnType("character varying(100000)")
                        .HasColumnName("justification_chiffre");

                    b.PrimitiveCollection<string[]>("Mesures")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("mesures");

                    b.Property<Guid>("PersonneId")
                        .HasColumnType("uuid")
                        .HasColumnName("personne_id");

                    b.Property<string>("Recommandations")
                        .HasMaxLength(100000)
                        .HasColumnType("character varying(100000)")
                        .HasColumnName("recommandations_chiffre");

                    b.Property<string>("ReferenceSignature")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("reference_signature");

                    b.Property<DateTimeOffset?>("SigneeLe")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("signee_le");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("statut");

                    b.Property<string>("TypeExamen")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("type_examen");

                    b.Property<DateOnly?>("ValideJusquAu")
                        .HasColumnType("date")
                        .HasColumnName("valide_jusqu_au");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("deleted_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTimeOffset>("updated_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("updated_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.Property<int>("version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_decision");

                    b.HasIndex("DossierId")
                        .HasDatabaseName("ix_decision_dossier_id");

                    b.HasIndex("ExamenId")
                        .IsUnique()
                        .HasDatabaseName("ix_decision_examen_id");

                    b.HasIndex("PersonneId")
                        .HasDatabaseName("ix_decision_personne_id");

                    b.ToTable("decision", (string)null);
                });

            modelBuilder.Entity("Sepp.SurveillanceMedicale.Domain.Decisions.Recours", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Commentaire")
                        .HasMaxLength(100000)
                        .HasColumnType("character varying(100000)")
                        .HasColumnName("commentaire_chiffre");

                    b.Property<DateOnly>("DateIntroduction")
                        .HasColumnType("date")
                        .HasColumnName("date_introduction");

                    b.Property<DateOnly?>("DateIssue")
                        .HasColumnType("date")
                        .HasColumnName("date_issue");

                    b.Property<DateOnly>("DateLimiteIntroduction")
                        .HasColumnType("date")
                        .HasColumnName("date_limite_introduction");

                    b.Property<DateOnly>("DateLimiteIssue")
                        .HasColumnType("date")
                        .HasColumnName("date_limite_issue");

                    b.Property<bool>("IntroduitDansLeDelai")
                        .HasColumnType("boolean")
                        .HasColumnName("introduit_dans_le_delai");

                    b.Property<string>("Issue")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("issue");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<Guid>("decision_id")
                        .HasColumnType("uuid")
                        .HasColumnName("decision_id");

                    b.Property<DateTimeOffset>("updated_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("updated_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.Property<int>("version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_recours");

                    b.HasIndex("decision_id")
                        .HasDatabaseName("ix_recours_decision_id");

                    b.ToTable("recours", (string)null);
                });

            modelBuilder.Entity("Sepp.SurveillanceMedicale.Domain.Dossiers.DossierSante", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("DateArchivage")
                        .HasColumnType("date")
                        .HasColumnName("date_archivage");

                    b.Property<DateOnly>("DateOuverture")
                        .HasColumnType("date")
                        .HasColumnName("date_ouverture");

                    b.Property<DateOnly?>("DatePurgePrevue")
                        .HasColumnType("date")
                        .HasColumnName("date_purge_prevue");

                    b.Property<string>("GestionnaireCpmtId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("gestionnaire_cpmt_id");

                    b.Property<Guid>("PersonneId")
                        .HasColumnType("uuid")
                        .HasColumnName("personne_id");

                    b.Property<string>("StatutArchivage")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("statut_archivage");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("deleted_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTimeOffset>("updated_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("updated_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.Property<int>("version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_dossier_sante");

                    b.HasIndex("PersonneId")
                        .IsUnique()
                        .HasDatabaseName("ix_dossier_sante_personne_id");

                    b.HasIndex("StatutArchivage")
                        .HasDatabaseName("ix_dossier_sante_statut_archivage");

                    b.ToTable("dossier_sante", (string)null);
                });

            modelBuilder.Entity("Sepp.SurveillanceMedicale.Domain.Dossiers.Exposition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Agent")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("agent");

                    b.Property<Guid?>("GroupeExpositionId")
                        .HasColumnType("uuid")
                        .HasColumnName("groupe_exposition_id");

                    b.Property<Guid?>("MesurageId")
                        .HasColumnType("uuid")
                        .HasColumnName("mesurage_id");

                    b.Property<string>("Niveau")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("niveau");

                    b.Property<DateOnly>("PeriodeDebut")
                        .HasColumnType("date")
                        .HasColumnName("periode_debut");

                    b.Property<DateOnly?>("PeriodeFin")
                        .HasColumnType("date")
                        .HasColumnName("periode_fin");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<Guid>("dossier_id")
                        .HasColumnType("uuid")
                        .HasColumnName("dossier_id");

                    b.Property<DateTimeOffset>("updated_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("updated_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.Property<int>("version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_exposition");

                    b.HasIndex("dossier_id", "MesurageId")
                        .IsUnique()
                        .HasDatabaseName("ix_exposition_dossier_id_mesurage_id")
                        .HasFilter("mesurage_id IS NOT NULL");

                    b.ToTable("exposition", (string)null);
                });

            modelBuilder.Entity("Sepp.SurveillanceMedicale.Domain.Dossiers.PieceJointe", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("AjouteeLe")
                        .HasColumnType("date")
                        .HasColumnName("ajoutee_le");

                    b.Property<string>("Categorie")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("categorie");

                    b.Property<DateOnly>("DateDocument")
                        .HasColumnType("date")
                        .HasColumnName("date_document");

                    b.Property<string>("Description")
                        .HasMaxLength(100000)
                        .HasColumnType("character varying(100000)")
                        .HasColumnName("description_chiffre");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(100000)
                        .HasColumnType("character varying(100000)")
                        .HasColumnName("titre_chiffre");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<Guid>("dossier_id")
                        .HasColumnType("uuid")
                        .HasColumnName("dossier_id");

                    b.Property<DateTimeOffset>("updated_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("updated_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.Property<int>("version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_piece_jointe");

                    b.HasIndex("dossier_id")
                        .HasDatabaseName("ix_piece_jointe_dossier_id");

                    b.ToTable("piece_jointe", (string)null);
                });

            modelBuilder.Entity("Sepp.SurveillanceMedicale.Domain.Dossiers.QuestionnaireRempli", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ExamenId")
                        .HasColumnType("uuid")
                        .HasColumnName("examen_id");

                    b.Property<string>("ModeleCode")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("modele_code");

                    b.Property<int>("ModeleVersion")
                        .HasColumnType("integer")
                        .HasColumnName("modele_version");

                    b.Property<DateTimeOffset>("RempliLe")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rempli_le");

                    b.Property<string>("Reponses")
                        .IsRequired()
                        .HasMaxLength(100000)
                        .HasColumnType("character varying(100000)")
                        .HasColumnName("reponses_chiffre");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("source");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<Guid>("dossier_id")
                        .HasColumnType("uuid")
                        .HasColumnName("dossier_id");

                    b.Property<DateTimeOffset>("updated_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("updated_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.Property<int>("version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_questionnaire_rempli");

                    b.HasIndex("dossier_id")
                        .HasDatabaseName("ix_questionnaire_rempli_dossier_id");

                    b.ToTable("questionnaire_rempli", (string)null);
                });

            modelBuilder.Entity("Sepp.SurveillanceMedicale.Domain.Dossiers.RattachementGroupeExposition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AffilieId")
                        .HasColumnType("uuid")
                        .HasColumnName("affilie_id");

                    b.Property<Guid>("GroupeExpositionId")
                        .HasColumnType("uuid")
                        .HasColumnName("groupe_exposition_id");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<Guid>("dossier_id")
                        .HasColumnType("uuid")
                        .HasColumnName("dossier_id");

                    b.Property<DateTimeOffset>("updated_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("updated_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.Property<int>("version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Periode", "Sepp.SurveillanceMedicale.Domain.Dossiers.RattachementGroupeExposition.Periode#Validity", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateOnly>("ValidFrom")
                                .HasColumnType("date")
                                .HasColumnName("valid_from");

                            b1.Property<DateOnly?>("ValidTo")
                                .HasColumnType("date")
                                .HasColumnName("valid_to");
                        });

                    b.HasKey("Id")
                        .HasName("pk_rattachement_groupe_exposition");

                    b.HasIndex("GroupeExpositionId")
                        .HasDatabaseName("ix_rattachement_groupe_exposition_groupe_exposition_id");

                    b.HasIndex("dossier_id")
                        .HasDatabaseName("ix_rattachement_groupe_exposition_dossier_id");

                    b.ToTable("rattachement_groupe_exposition", (string)null);
                });

            modelBuilder.Entity("Sepp.SurveillanceMedicale.Domain.Dossiers.TestTuberculinique", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("DateLecture")
                        .HasColumnType("date")
                        .HasColumnName("date_lecture");

                    b.Property<DateOnly>("DatePose")
                        .HasColumnType("date")
                        .HasColumnName("date_pose");

                    b.Property<string>("Lecture")
                        .HasMaxLength(100000)
                        .HasColumnType("character varying(100000)")
                        .HasColumnName("lecture_chiffre");

                    b.Property<string>("RealisePar")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("realise_par");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<Guid>("dossier_id")
                        .HasColumnType("uuid")
                        .HasColumnName("dossier_id");

                    b.Property<DateTimeOffset>("updated_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("updated_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.Property<int>("version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_test_tuberculinique");

                    b.HasIndex("dossier_id")
                        .HasDatabaseName("ix_test_tuberculinique_dossier_id");

                    b.ToTable("test_tuberculinique", (string)null);
                });

            modelBuilder.Entity("Sepp.SurveillanceMedicale.Domain.Dossiers.Vaccination", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AdministrePar")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("administre_par");

                    b.Property<Guid?>("CentreId")
                        .HasColumnType("uuid")
                        .HasColumnName("centre_id");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<int>("Dose")
                        .HasColumnType("integer")
                        .HasColumnName("dose");

                    b.Property<bool>("EnregistreRegistre")
                        .HasColumnType("boolean")
                        .HasColumnName("enregistre_registre");

                    b.Property<Guid?>("LotId")
                        .HasColumnType("uuid")
                        .HasColumnName("lot_id");

                    b.Property<string>("Remarque")
                        .HasMaxLength(100000)
                        .HasColumnType("character varying(100000)")
                        .HasColumnName("remarque_chiffre");

                    b.Property<string>("VaccinCode")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("vaccin_code");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<Guid>("dossier_id")
                        .HasColumnType("uuid")
                        .HasColumnName("dossier_id");

                    b.Property<DateTimeOffset>("updated_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("updated_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.Property<int>("version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_vaccination");

                    b.HasIndex("LotId")
                        .HasDatabaseName("ix_vaccination_lot_id");

                    b.HasIndex("dossier_id")
                        .HasDatabaseName("ix_vaccination_dossier_id");

                    b.ToTable("vaccination", (string)null);
                });

            modelBuilder.Entity("Sepp.SurveillanceMedicale.Domain.Examens.Examen", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AffilieId")
                        .HasColumnType("uuid")
                        .HasColumnName("affilie_id");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<DateOnly?>("DateCloture")
                        .HasColumnType("date")
                        .HasColumnName("date_cloture");

                    b.Property<Guid>("DossierId")
                        .HasColumnType("uuid")
                        .HasColumnName("dossier_id");

                    b.Property<bool?>("HorsDelaiLegal")
                        .HasColumnType("boolean")
                        .HasColumnName("hors_delai_legal");

                    b.PrimitiveCollection<Guid[]>("ObligationIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("obligation_ids");

                    b.Property<Guid>("PersonneId")
                        .HasColumnType("uuid")
                        .HasColumnName("personne_id");

                    b.Property<string>("ProfessionnelId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("professionnel_id");

                    b.Property<Guid?>("RendezVousId")
                        .HasColumnType("uuid")
                        .HasColumnName("rendez_vous_id");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("statut");

                    b.Property<string>("TypeExamen")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("type_examen");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("deleted_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTimeOffset>("updated_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("updated_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.Property<int>("version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_examen");

                    b.HasIndex("PersonneId")
                        .HasDatabaseName("ix_examen_personne_id");

                    b.HasIndex("DossierId", "ProfessionnelId")
                        .HasDatabaseName("ix_examen_dossier_id_professionnel_id");

                    b.ToTable("examen", (string)null);
                });

            modelBuilder.Entity("Sepp.SurveillanceMedicale.Domain.Examens.ObservationClinique", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Anamnese")
                        .HasMaxLength(100000)
                        .HasColumnType("character varying(100000)")
                        .HasColumnName("anamnese_chiffre");

                    b.Property<string>("ExamenClinique")
                        .HasMaxLength(100000)
                        .HasColumnType("character varying(100000)")
                        .HasColumnName("examen_clinique_chiffre");

                    b.Property<DateTimeOffset>("SaisieLe")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("saisie_le");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<Guid>("examen_id")
                        .HasColumnType("uuid")
                        .HasColumnName("examen_id");

                    b.Property<DateTimeOffset>("updated_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("updated_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.Property<int>("version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_observation_clinique");

                    b.HasIndex("examen_id")
                        .IsUnique()
                        .HasDatabaseName("ix_observation_clinique_examen_id");

                    b.ToTable("observation_clinique", (string)null);
                });

            modelBuilder.Entity("Sepp.SurveillanceMedicale.Domain.Examens.PropositionFrequence", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("DateDecision")
                        .HasColumnType("date")
                        .HasColumnName("date_decision");

                    b.Property<DateOnly>("DateProposition")
                        .HasColumnType("date")
                        .HasColumnName("date_proposition");

                    b.Property<string>("DecidePar")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("decide_par");

                    b.Property<Guid>("ResultatActeId")
                        .HasColumnType("uuid")
                        .HasColumnName("resultat_acte_id");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("statut");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<Guid>("examen_id")
                        .HasColumnType("uuid")
                        .HasColumnName("examen_id");

                    b.Property<DateTimeOffset>("updated_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("updated_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.Property<int>("version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_proposition_frequence");

                    b.HasIndex("examen_id")
                        .HasDatabaseName("ix_proposition_frequence_examen_id");

                    b.ToTable("proposition_frequence", (string)null);
                });

            modelBuilder.Entity("Sepp.SurveillanceMedicale.Domain.Examens.ResultatActe", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Commentaire")
                        .HasMaxLength(100000)
                        .HasColumnType("character varying(100000)")
                        .HasColumnName("commentaire_chiffre");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<bool>("Inhabituel")
                        .HasColumnType("boolean")
                        .HasColumnName("inhabituel");

                    b.Property<string>("Mesures")
                        .IsRequired()
                        .HasMaxLength(100000)
                        .HasColumnType("character varying(100000)")
                        .HasColumnName("valeurs_chiffre");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("source");

                    b.Property<string>("TypeActe")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("type_acte");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<Guid>("examen_id")
                        .HasColumnType("uuid")
                        .HasColumnName("examen_id");

                    b.Property<DateTimeOffset>("updated_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("updated_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.Property<int>("version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_resultat_acte");

                    b.HasIndex("examen_id")
                        .HasDatabaseName("ix_resultat_acte_examen_id");

                    b.ToTable("resultat_acte", (string)null);
                });

            modelBuilder.Entity("Sepp.SurveillanceMedicale.Domain.MaladiesProfessionnelles.DeclarationMaladieProfessionnelle", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AuteurId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("auteur_id");

                    b.Property<string>("Contenu")
                        .IsRequired()
                        .HasMaxLength(100000)
                        .HasColumnType("character varying(100000)")
                        .HasColumnName("contenu_chiffre");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<DateOnly?>("DateEnvoi")
                        .HasColumnType("date")
                        .HasColumnName("date_envoi");

                    b.Property<DateOnly?>("DateIssue")
                        .HasColumnType("date")
                        .HasColumnName("date_issue");

                    b.Property<Guid>("DossierId")
                        .HasColumnType("uuid")
                        .HasColumnName("dossier_id");

                    b.Property<Guid>("PersonneId")
                        .HasColumnType("uuid")
                        .HasColumnName("personne_id");

                    b.Property<string>("ReferenceFedris")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reference_fedris");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("statut");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("deleted_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTimeOffset>("updated_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("updated_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.Property<int>("version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_declaration_mp");

                    b.HasIndex("DossierId")
                        .HasDatabaseName("ix_declaration_mp_dossier_id");

                    b.ToTable("declaration_mp", (string)null);
                });

            modelBuilder.Entity("Sepp.SurveillanceMedicale.Domain.MaladiesProfessionnelles.DemandeInformationFedris", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("DateDemande")
                        .HasColumnType("date")
                        .HasColumnName("date_demande");

                    b.Property<DateOnly?>("DateReponse")
                        .HasColumnType("date")
                        .HasColumnName("date_reponse");

                    b.Property<DateOnly?>("Echeance")
                        .HasColumnType("date")
                        .HasColumnName("echeance");

                    b.Property<string>("Objet")
                        .IsRequired()
                        .HasMaxLength(100000)
                        .HasColumnType("character varying(100000)")
                        .HasColumnName("objet_chiffre");

                    b.Property<string>("Reponse")
                        .HasMaxLength(100000)
                        .HasColumnType("character varying(100000)")
                        .HasColumnName("reponse_chiffre");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<Guid>("declaration_mp_id")
                        .HasColumnType("uuid")
                        .HasColumnName("declaration_mp_id");

                    b.Property<DateTimeOffset>("updated_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("updated_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.Property<int>("version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_demande_information_fedris");

                    b.HasIndex("declaration_mp_id")
                        .HasDatabaseName("ix_demande_information_fedris_declaration_mp_id");

                    b.ToTable("demande_information_fedris", (string)null);
                });

            modelBuilder.Entity("Sepp.SurveillanceMedicale.Domain.Projections.AffectationPersonne", b =>
                {
                    b.Property<Guid>("AffectationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("affectation_id");

                    b.Property<DateOnly>("DateDebut")
                        .HasColumnType("date")
                        .HasColumnName("date_debut");

                    b.Property<DateOnly?>("DateFin")
                        .HasColumnType("date")
                        .HasColumnName("date_fin");

                    b.Property<DateTimeOffset>("EvenementDu")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("evenement_du");

                    b.Property<Guid>("PersonneId")
                        .HasColumnType("uuid")
                        .HasColumnName("personne_id");

                    b.Property<Guid>("PosteId")
                        .HasColumnType("uuid")
                        .HasColumnName("poste_id");

                    b.HasKey("AffectationId")
                        .HasName("pk_affectation_personne");

                    b.HasIndex("PersonneId")
                        .HasDatabaseName("ix_affectation_personne_personne_id");

                    b.ToTable("affectation_personne", (string)null);
                });

            modelBuilder.Entity("Sepp.SurveillanceMedicale.Domain.Projections.MesurageExposition", b =>
                {
                    b.Property<Guid>("MesurageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("mesurage_id");

                    b.Property<Guid>("AffilieId")
                        .HasColumnType("uuid")
                        .HasColumnName("affilie_id");

                    b.Property<string>("Agent")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("agent");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<Guid>("GroupeExpositionId")
                        .HasColumnType("uuid")
                        .HasColumnName("groupe_exposition_id");

                    b.Property<string>("Niveau")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("niveau");

                    b.HasKey("MesurageId")
                        .HasName("pk_mesurage_exposition");

                    b.HasIndex("GroupeExpositionId")
                        .HasDatabaseName("ix_mesurage_exposition_groupe_exposition_id");

                    b.ToTable("mesurage_exposition", (string)null);
                });

            modelBuilder.Entity("Sepp.SurveillanceMedicale.Domain.Projections.ObligationDue", b =>
                {
                    b.Property<Guid>("ObligationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("obligation_id");

                    b.Property<Guid>("AffilieId")
                        .HasColumnType("uuid")
                        .HasColumnName("affilie_id");

                    b.Property<DateOnly>("DateDue")
                        .HasColumnType("date")
                        .HasColumnName("date_due");

                    b.Property<DateOnly?>("DateLimite")
                        .HasColumnType("date")
                        .HasColumnName("date_limite");

                    b.Property<Guid>("PersonneId")
                        .HasColumnType("uuid")
                        .HasColumnName("personne_id");

                    b.Property<Guid?>("SatisfaiteParExamenId")
                        .HasColumnType("uuid")
                        .HasColumnName("satisfaite_par_examen_id");

                    b.Property<string>("TypeExamen")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("type_examen");

                    b.HasKey("ObligationId")
                        .HasName("pk_obligation_due");

                    b.HasIndex("PersonneId")
                        .HasDatabaseName("ix_obligation_due_personne_id");

                    b.ToTable("obligation_due", (string)null);
                });

            modelBuilder.Entity("Sepp.SurveillanceMedicale.Domain.Projections.ParametreLegalLocal", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<DateOnly>("ValideDu")
                        .HasColumnType("date")
                        .HasColumnName("valide_du");

                    b.Property<string>("Unite")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("unite");

                    b.Property<decimal>("Valeur")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("valeur");

                    b.Property<DateOnly?>("ValideJusquAu")
                        .HasColumnType("date")
                        .HasColumnName("valide_jusqu_au");

                    b.HasKey("Code", "ValideDu")
                        .HasName("pk_parametre_legal_local");

                    b.ToTable("parametre_legal_local", (string)null);
                });

            modelBuilder.Entity("Sepp.SurveillanceMedicale.Domain.Projections.ProfilRisquePoste", b =>
                {
                    b.Property<Guid>("PosteId")
                        .HasColumnType("uuid")
                        .HasColumnName("poste_id");

                    b.Property<DateOnly>("ValideDu")
                        .HasColumnType("date")
                        .HasColumnName("valide_du");

                    b.Property<Guid>("AffilieId")
                        .HasColumnType("uuid")
                        .HasColumnName("affilie_id");

                    b.PrimitiveCollection<string[]>("CodesRisques")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("codes_risques");

                    b.HasKey("PosteId", "ValideDu")
                        .HasName("pk_profil_risque_poste");

                    b.ToTable("profil_risque_poste", (string)null);
                });

            modelBuilder.Entity("Sepp.SurveillanceMedicale.Domain.Projections.RendezVousPrevu", b =>
                {
                    b.Property<Guid>("RendezVousId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("rendez_vous_id");

                    b.Property<Guid>("AffilieId")
                        .HasColumnType("uuid")
                        .HasColumnName("affilie_id");

                    b.Property<DateTimeOffset>("Debut")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("debut");

                    b.PrimitiveCollection<Guid[]>("ObligationIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("obligation_ids");

                    b.Property<Guid>("PersonneId")
                        .HasColumnType("uuid")
                        .HasColumnName("personne_id");

                    b.HasKey("RendezVousId")
                        .HasName("pk_rendez_vous_prevu");

                    b.HasIndex("PersonneId")
                        .HasDatabaseName("ix_rendez_vous_prevu_personne_id");

                    b.ToTable("rendez_vous_prevu", (string)null);
                });

            modelBuilder.Entity("Sepp.SurveillanceMedicale.Domain.Protocoles.ModeleQuestionnaire", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("code");

                    b.Property<string>("Questions")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("questions");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("deleted_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTimeOffset>("updated_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("updated_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.Property<int>("version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Titre", "Sepp.SurveillanceMedicale.Domain.Protocoles.ModeleQuestionnaire.Titre#LocalizedLabel", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("De")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("titre_de");

                            b1.Property<string>("En")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("titre_en");

                            b1.Property<string>("Fr")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("titre_fr");

                            b1.Property<string>("Nl")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("titre_nl");
                        });

                    b.HasKey("Id")
                        .HasName("pk_modele_questionnaire");

                    b.HasIndex("Code", "Version")
                        .IsUnique()
                        .HasDatabaseName("ix_modele_questionnaire_code_version");

                    b.ToTable("modele_questionnaire", null, t =>
                        {
                            t.Property("version")
                                .HasColumnName("version1");
                        });
                });

            modelBuilder.Entity("Sepp.SurveillanceMedicale.Domain.Protocoles.ModeleTexte", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("code");

                    b.Property<string>("CpmtId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cpmt_id");

                    b.Property<string>("Rubrique")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("rubrique");

                    b.Property<string>("Texte")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("texte");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("titre");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("deleted_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTimeOffset>("updated_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("updated_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.Property<int>("version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_modele_texte");

                    b.HasIndex("CpmtId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_modele_texte_cpmt_id_code")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("modele_texte", (string)null);
                });

            modelBuilder.Entity("Sepp.SurveillanceMedicale.Domain.Protocoles.ValeurReference", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CodeMesure")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("code_mesure");

                    b.Property<decimal?>("Maximum")
                        .HasColumnType("numeric")
                        .HasColumnName("maximum");

                    b.Property<decimal?>("Minimum")
                        .HasColumnType("numeric")
                        .HasColumnName("minimum");

                    b.Property<string>("TypeActe")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("type_acte");

                    b.Property<string>("Unite")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("unite");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("deleted_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTimeOffset>("updated_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("updated_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.Property<int>("version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Libelle", "Sepp.SurveillanceMedicale.Domain.Protocoles.ValeurReference.Libelle#LocalizedLabel", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("De")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("libelle_de");

                            b1.Property<string>("En")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("libelle_en");

                            b1.Property<string>("Fr")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("libelle_fr");

                            b1.Property<string>("Nl")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("libelle_nl");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Validite", "Sepp.SurveillanceMedicale.Domain.Protocoles.ValeurReference.Validite#Validity", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateOnly>("ValidFrom")
                                .HasColumnType("date")
                                .HasColumnName("valid_from");

                            b1.Property<DateOnly?>("ValidTo")
                                .HasColumnType("date")
                                .HasColumnName("valid_to");
                        });

                    b.HasKey("Id")
                        .HasName("pk_valeur_reference");

                    b.HasIndex("TypeActe", "CodeMesure")
                        .HasDatabaseName("ix_valeur_reference_type_acte_code_mesure");

                    b.ToTable("valeur_reference", (string)null);
                });

            modelBuilder.Entity("Sepp.SurveillanceMedicale.Domain.Transferts.TransfertDossier", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Contrepartie")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("contrepartie");

                    b.Property<DateOnly>("DateDemande")
                        .HasColumnType("date")
                        .HasColumnName("date_demande");

                    b.Property<DateOnly?>("DateIntegration")
                        .HasColumnType("date")
                        .HasColumnName("date_integration");

                    b.Property<DateOnly?>("DateTransmission")
                        .HasColumnType("date")
                        .HasColumnName("date_transmission");

                    b.Property<string>("DemandePar")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("demande_par");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("direction");

                    b.Property<Guid>("DossierId")
                        .HasColumnType("uuid")
                        .HasColumnName("dossier_id");

                    b.Property<string>("Empreinte")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("empreinte");

                    b.Property<string>("Motif")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("motif");

                    b.Property<string>("Paquet")
                        .HasColumnType("text")
                        .HasColumnName("paquet_chiffre");

                    b.Property<Guid>("PersonneId")
                        .HasColumnType("uuid")
                        .HasColumnName("personne_id");

                    b.Property<string>("ReferenceCanal")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("reference_canal");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("statut");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("deleted_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTimeOffset>("updated_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("updated_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.Property<int>("version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_transfert_dossier");

                    b.HasIndex("DossierId")
                        .HasDatabaseName("ix_transfert_dossier_dossier_id");

                    b.ToTable("transfert_dossier", (string)null);
                });

            modelBuilder.Entity("Sepp.SurveillanceMedicale.Domain.Vaccinations.LotVaccin", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CentreId")
                        .HasColumnType("uuid")
                        .HasColumnName("centre_id");

                    b.Property<string>("NumeroLot")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("numero_lot");

                    b.Property<DateOnly>("Peremption")
                        .HasColumnType("date")
                        .HasColumnName("peremption");

                    b.Property<int>("QuantiteInitiale")
                        .HasColumnType("integer")
                        .HasColumnName("quantite_initiale");

                    b.Property<int>("QuantiteRestante")
                        .HasColumnType("integer")
                        .HasColumnName("quantite_restante");

                    b.Property<string>("VaccinCode")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("vaccin_code");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("deleted_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTimeOffset>("updated_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("updated_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.Property<int>("version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_lot_vaccin");

                    b.HasIndex("CentreId", "VaccinCode", "NumeroLot")
                        .IsUnique()
                        .HasDatabaseName("ix_lot_vaccin_centre_id_vaccin_code_numero_lot");

                    b.ToTable("lot_vaccin", (string)null);
                });

            modelBuilder.Entity("Sepp.SurveillanceMedicale.Domain.Vaccinations.SchemaVaccinal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.PrimitiveCollection<string[]>("CodesRisques")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("codes_risques");

                    b.PrimitiveCollection<int[]>("IntervallesMois")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("intervalles_mois");

                    b.Property<int>("NombreDoses")
                        .HasColumnType("integer")
                        .HasColumnName("nombre_doses");

                    b.Property<int?>("RappelMois")
                        .HasColumnType("integer")
                        .HasColumnName("rappel_mois");

                    b.Property<string>("VaccinCode")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("vaccin_code");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("deleted_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTimeOffset>("updated_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("updated_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.Property<int>("version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Libelle", "Sepp.SurveillanceMedicale.Domain.Vaccinations.SchemaVaccinal.Libelle#LocalizedLabel", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("De")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("libelle_de");

                            b1.Property<string>("En")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("libelle_en");

                            b1.Property<string>("Fr")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("libelle_fr");

                            b1.Property<string>("Nl")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("libelle_nl");
                        });

                    b.HasKey("Id")
                        .HasName("pk_schema_vaccinal");

                    b.ToTable("schema_vaccinal", (string)null);
                });

            modelBuilder.Entity("Sepp.SurveillanceMedicale.Domain.Decisions.Decision", b =>
                {
                    b.HasOne("Sepp.SurveillanceMedicale.Domain.Examens.Examen", null)
                        .WithMany()
                        .HasForeignKey("ExamenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_decision_examen_examen_id");
                });

            modelBuilder.Entity("Sepp.SurveillanceMedicale.Domain.Decisions.Recours", b =>
                {
                    b.HasOne("Sepp.SurveillanceMedicale.Domain.Decisions.Decision", null)
                        .WithMany("Recours")
                        .HasForeignKey("decision_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recours_decision_decision_id");
                });

            modelBuilder.Entity("Sepp.SurveillanceMedicale.Domain.Dossiers.Exposition", b =>
                {
                    b.HasOne("Sepp.SurveillanceMedicale.Domain.Dossiers.DossierSante", null)
                        .WithMany("Expositions")
                        .HasForeignKey("dossier_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_exposition_dossier_sante_dossier_id");
                });

            modelBuilder.Entity("Sepp.SurveillanceMedicale.Domain.Dossiers.PieceJointe", b =>
                {
                    b.HasOne("Sepp.SurveillanceMedicale.Domain.Dossiers.DossierSante", null)
                        .WithMany("PiecesJointes")
                        .HasForeignKey("dossier_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_piece_jointe_dossier_sante_dossier_id");
                });

            modelBuilder.Entity("Sepp.SurveillanceMedicale.Domain.Dossiers.QuestionnaireRempli", b =>
                {
                    b.HasOne("Sepp.SurveillanceMedicale.Domain.Dossiers.DossierSante", null)
                        .WithMany("Questionnaires")
                        .HasForeignKey("dossier_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_questionnaire_rempli_dossier_sante_dossier_id");
                });

            modelBuilder.Entity("Sepp.SurveillanceMedicale.Domain.Dossiers.RattachementGroupeExposition", b =>
                {
                    b.HasOne("Sepp.SurveillanceMedicale.Domain.Dossiers.DossierSante", null)
                        .WithMany("GroupesExposition")
                        .HasForeignKey("dossier_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rattachement_groupe_exposition_dossier_sante_dossier_id");
                });

            modelBuilder.Entity("Sepp.SurveillanceMedicale.Domain.Dossiers.TestTuberculinique", b =>
                {
                    b.HasOne("Sepp.SurveillanceMedicale.Domain.Dossiers.DossierSante", null)
                        .WithMany("TestsTuberculiniques")
                        .HasForeignKey("dossier_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_test_tuberculinique_dossier_sante_dossier_id");
                });

            modelBuilder.Entity("Sepp.SurveillanceMedicale.Domain.Dossiers.Vaccination", b =>
                {
                    b.HasOne("Sepp.SurveillanceMedicale.Domain.Vaccinations.LotVaccin", null)
                        .WithMany()
                        .HasForeignKey("LotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_vaccination_lots_vaccins_lot_id");

                    b.HasOne("Sepp.SurveillanceMedicale.Domain.Dossiers.DossierSante", null)
                        .WithMany("Vaccinations")
                        .HasForeignKey("dossier_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vaccination_dossier_sante_dossier_id");
                });

            modelBuilder.Entity("Sepp.SurveillanceMedicale.Domain.Examens.Examen", b =>
                {
                    b.HasOne("Sepp.SurveillanceMedicale.Domain.Dossiers.DossierSante", null)
                        .WithMany()
                        .HasForeignKey("DossierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_examen_dossier_sante_dossier_id");
                });

            modelBuilder.Entity("Sepp.SurveillanceMedicale.Domain.Examens.ObservationClinique", b =>
                {
                    b.HasOne("Sepp.SurveillanceMedicale.Domain.Examens.Examen", null)
                        .WithOne("Observation")
                        .HasForeignKey("Sepp.SurveillanceMedicale.Domain.Examens.ObservationClinique", "examen_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_observation_clinique_examen_examen_id");
                });

            modelBuilder.Entity("Sepp.SurveillanceMedicale.Domain.Examens.PropositionFrequence", b =>
                {
                    b.HasOne("Sepp.SurveillanceMedicale.Domain.Examens.Examen", null)
                        .WithMany("PropositionsFrequence")
                        .HasForeignKey("examen_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_proposition_frequence_examen_examen_id");
                });

            modelBuilder.Entity("Sepp.SurveillanceMedicale.Domain.Examens.ResultatActe", b =>
                {
                    b.HasOne("Sepp.SurveillanceMedicale.Domain.Examens.Examen", null)
                        .WithMany("Resultats")
                        .HasForeignKey("examen_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_resultat_acte_examen_examen_id");
                });

            modelBuilder.Entity("Sepp.SurveillanceMedicale.Domain.MaladiesProfessionnelles.DeclarationMaladieProfessionnelle", b =>
                {
                    b.HasOne("Sepp.SurveillanceMedicale.Domain.Dossiers.DossierSante", null)
                        .WithMany()
                        .HasForeignKey("DossierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_declaration_mp_dossier_sante_dossier_id");
                });

            modelBuilder.Entity("Sepp.SurveillanceMedicale.Domain.MaladiesProfessionnelles.DemandeInformationFedris", b =>
                {
                    b.HasOne("Sepp.SurveillanceMedicale.Domain.MaladiesProfessionnelles.DeclarationMaladieProfessionnelle", null)
                        .WithMany("DemandesInformation")
                        .HasForeignKey("declaration_mp_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_demande_information_fedris_declaration_mp_declaration_mp_id");
                });

            modelBuilder.Entity("Sepp.SurveillanceMedicale.Domain.Transferts.TransfertDossier", b =>
                {
                    b.HasOne("Sepp.SurveillanceMedicale.Domain.Dossiers.DossierSante", null)
                        .WithMany()
                        .HasForeignKey("DossierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_transfert_dossier_dossier_sante_dossier_id");
                });

            modelBuilder.Entity("Sepp.SurveillanceMedicale.Domain.Decisions.Decision", b =>
                {
                    b.Navigation("Recours");
                });

            modelBuilder.Entity("Sepp.SurveillanceMedicale.Domain.Dossiers.DossierSante", b =>
                {
                    b.Navigation("Expositions");

                    b.Navigation("GroupesExposition");

                    b.Navigation("PiecesJointes");

                    b.Navigation("Questionnaires");

                    b.Navigation("TestsTuberculiniques");

                    b.Navigation("Vaccinations");
                });

            modelBuilder.Entity("Sepp.SurveillanceMedicale.Domain.Examens.Examen", b =>
                {
                    b.Navigation("Observation");

                    b.Navigation("PropositionsFrequence");

                    b.Navigation("Resultats");
                });

            modelBuilder.Entity("Sepp.SurveillanceMedicale.Domain.MaladiesProfessionnelles.DeclarationMaladieProfessionnelle", b =>
                {
                    b.Navigation("DemandesInformation");
                });
#pragma warning restore 612, 618
        }
    }
}
