<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="Shouldly" />
    <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Sepp.Affilies.Infrastructure\Sepp.Affilies.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\..\..\tests\Sepp.Testing.Architecture\Sepp.Testing.Architecture.csproj" />
  </ItemGroup>
</Project>
