<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <AssemblyName>Sepp.Integrations</AssemblyName>
    <RootNamespace>Sepp.Integrations.Infrastructure</RootNamespace>
    <UserSecretsId>sepp-integrations</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" PrivateAssets="all" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Sepp.Integrations.Adapters\Sepp.Integrations.Adapters.csproj" />
  </ItemGroup>
</Project>
