<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Sepp.Communications.Domain\Sepp.Communications.Domain.csproj" />
    <ProjectReference Include="..\..\..\..\BuildingBlocks\Sepp.BuildingBlocks.Application\Sepp.BuildingBlocks.Application.csproj" />
  </ItemGroup>
</Project>
