// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sepp.Integrations.Adapters.Persistence;

#nullable disable

namespace Sepp.Integrations.Adapters.Persistence.Migrations
{
    [DbContext(typeof(IntegrationsDbContext))]
    partial class IntegrationsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sepp.BuildingBlocks.Infrastructure.Messaging.InboxMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<string>("Consumer")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("consumer");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.HasKey("MessageId", "Consumer")
                        .HasName("pk_inbox_message");

                    b.ToTable("inbox_message", (string)null);
                });

            modelBuilder.Entity("Sepp.BuildingBlocks.Infrastructure.Messaging.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("event_type");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("topic");

                    b.HasKey("Id")
                        .HasName("pk_outbox_message");

                    b.HasIndex("ProcessedAt")
                        .HasDatabaseName("ix_outbox_message_processed_at")
                        .HasFilter("processed_at IS NULL");

                    b.ToTable("outbox_message", (string)null);
                });

            modelBuilder.Entity("Sepp.Integrations.Domain.Bce.EntrepriseBce", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ActualiseeLe")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualisee_le");

                    b.Property<string>("CodeNace")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("code_nace");

                    b.Property<DateOnly>("DateExtraction")
                        .HasColumnType("date")
                        .HasColumnName("date_extraction");

                    b.Property<string>("Denomination")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("denomination");

                    b.Property<string>("FormeJuridique")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("forme_juridique");

                    b.Property<string>("NumeroBce")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("numero_bce");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("deleted_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTimeOffset>("updated_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("updated_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.Property<int>("version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_entreprise_bce");

                    b.HasIndex("NumeroBce")
                        .IsUnique()
                        .HasDatabaseName("ix_entreprise_bce_numero_bce");

                    b.ToTable("entreprise_bce", (string)null);
                });

            modelBuilder.Entity("Sepp.Integrations.Domain.Bce.UniteEtablissementBce", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("DateDebut")
                        .HasColumnType("date")
                        .HasColumnName("date_debut");

                    b.Property<string>("Denomination")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("denomination");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("numero");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<Guid>("entreprise_bce_id")
                        .HasColumnType("uuid")
                        .HasColumnName("entreprise_bce_id");

                    b.Property<DateTimeOffset>("updated_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("updated_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.Property<int>("version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Adresse", "Sepp.Integrations.Domain.Bce.UniteEtablissementBce.Adresse#AdresseBce", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Boite")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("adresse_boite");

                            b1.Property<string>("CodePays")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)")
                                .HasColumnName("adresse_code_pays");

                            b1.Property<string>("CodePostal")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("adresse_code_postal");

                            b1.Property<string>("Localite")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("adresse_localite");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("adresse_numero");

                            b1.Property<string>("Rue")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("adresse_rue");
                        });

                    b.HasKey("Id")
                        .HasName("pk_unite_etablissement_bce");

                    b.HasIndex("entreprise_bce_id")
                        .HasDatabaseName("ix_unite_etablissement_bce_entreprise_bce_id");

                    b.ToTable("unite_etablissement_bce", (string)null);
                });

            modelBuilder.Entity("Sepp.Integrations.Domain.Correspondances.CorrespondanceIdentifiant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("IdentifiantInterne")
                        .HasColumnType("uuid")
                        .HasColumnName("identifiant_interne");

                    b.Property<string>("TypeExterne")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type_externe");

                    b.Property<string>("TypeInterne")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type_interne");

                    b.Property<string>("ValeurExterne")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("valeur_externe");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("deleted_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTimeOffset>("updated_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("updated_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.Property<int>("version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_correspondance_identifiant");

                    b.HasIndex("TypeExterne", "ValeurExterne")
                        .IsUnique()
                        .HasDatabaseName("ix_correspondance_identifiant_type_externe_valeur_externe");

                    b.HasIndex("TypeInterne", "IdentifiantInterne")
                        .HasDatabaseName("ix_correspondance_identifiant_type_interne_identifiant_interne");

                    b.ToTable("correspondance_identifiant", (string)null);
                });

            modelBuilder.Entity("Sepp.Integrations.Domain.Flux.EchangeFlux", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ChargeUtile")
                        .HasColumnType("text")
                        .HasColumnName("charge_utile_chiffree");

                    b.Property<DateTimeOffset?>("ChargeUtilePurgeeLe")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("charge_utile_purgee_le");

                    b.Property<string>("CleIdempotence")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("cle_idempotence");

                    b.Property<string>("CodeErreur")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code_erreur");

                    b.Property<DateTimeOffset?>("DerniereTentativeLe")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("derniere_tentative_le");

                    b.Property<string>("Flux")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("flux");

                    b.Property<string>("MessageErreur")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("message_erreur");

                    b.Property<int>("NombreEnregistrements")
                        .HasColumnType("integer")
                        .HasColumnName("nombre_enregistrements");

                    b.Property<DateTimeOffset>("RecuLe")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recu_le");

                    b.Property<string>("ReferenceExterne")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reference_externe");

                    b.Property<string>("Sens")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("sens");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("statut");

                    b.Property<int>("Tentatives")
                        .HasColumnType("integer")
                        .HasColumnName("tentatives");

                    b.Property<DateTimeOffset?>("TraiteLe")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("traite_le");

                    b.Property<string>("TypeMessage")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type_message");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("deleted_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTimeOffset>("updated_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("updated_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.Property<int>("version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_journal_flux");

                    b.HasIndex("RecuLe")
                        .HasDatabaseName("ix_journal_flux_recu_le");

                    b.HasIndex("Flux", "CleIdempotence")
                        .IsUnique()
                        .HasDatabaseName("ix_journal_flux_flux_cle_idempotence");

                    b.HasIndex("Flux", "Statut", "RecuLe")
                        .HasDatabaseName("ix_journal_flux_flux_statut_recu_le");

                    b.ToTable("journal_flux", (string)null);
                });

            modelBuilder.Entity("Sepp.Integrations.Domain.Flux.PositionFlux", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Flux")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("flux");

                    b.Property<DateTimeOffset?>("MiseAJourLe")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("mise_a_jour_le");

                    b.Property<string>("Position")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("position");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("deleted_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTimeOffset>("updated_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("updated_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.Property<int>("version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_position_flux");

                    b.HasIndex("Flux")
                        .IsUnique()
                        .HasDatabaseName("ix_position_flux_flux");

                    b.ToTable("position_flux", (string)null);
                });

            modelBuilder.Entity("Sepp.Integrations.Domain.Bce.UniteEtablissementBce", b =>
                {
                    b.HasOne("Sepp.Integrations.Domain.Bce.EntrepriseBce", null)
                        .WithMany("UnitesEtablissement")
                        .HasForeignKey("entreprise_bce_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_unite_etablissement_bce_entreprise_bce_entreprise_bce_id");
                });

            modelBuilder.Entity("Sepp.Integrations.Domain.Bce.EntrepriseBce", b =>
                {
                    b.Navigation("UnitesEtablissement");
                });
#pragma warning restore 612, 618
        }
    }
}
