<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <!-- MailKit (MIT) : envoi SMTP réel. -->
    <PackageReference Include="MailKit" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Sepp.Communications.Application\Sepp.Communications.Application.csproj" />
    <ProjectReference Include="..\..\..\..\BuildingBlocks\Sepp.BuildingBlocks.Infrastructure\Sepp.BuildingBlocks.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\..\BuildingBlocks\Sepp.BuildingBlocks.Web\Sepp.BuildingBlocks.Web.csproj" />
  </ItemGroup>
</Project>
