// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sepp.Affilies.Adapters.Persistence;

#nullable disable

namespace Sepp.Affilies.Adapters.Persistence.Migrations
{
    [DbContext(typeof(AffiliesDbContext))]
    partial class AffiliesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sepp.Affilies.Domain.Affilies.Affilie", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CategorieTarifaire")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("categorie_tarifaire");

                    b.Property<string>("CodeNace")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("code_nace");

                    b.Property<string>("CommissionParitaire")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("commission_paritaire");

                    b.Property<DateOnly>("DateAffiliation")
                        .HasColumnType("date")
                        .HasColumnName("date_affiliation");

                    b.Property<DateOnly?>("DateFin")
                        .HasColumnType("date")
                        .HasColumnName("date_fin");

                    b.Property<string>("Denomination")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("denomination");

                    b.Property<string>("FormeJuridique")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("forme_juridique");

                    b.Property<Guid?>("GroupeId")
                        .HasColumnType("uuid")
                        .HasColumnName("groupe_id");

                    b.Property<string>("Langue")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("langue");

                    b.Property<string>("NumeroBce")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("numero_bce");

                    b.Property<int>("NumeroVersion")
                        .HasColumnType("integer")
                        .HasColumnName("numero_version");

                    b.Property<string>("RegimeLinguistique")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("regime_linguistique");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("statut");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("deleted_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTimeOffset>("updated_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("updated_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.Property<int>("version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_affilie");

                    b.HasIndex("Denomination")
                        .HasDatabaseName("ix_affilie_denomination");

                    b.HasIndex("GroupeId")
                        .HasDatabaseName("ix_affilie_groupe_id");

                    b.HasIndex("NumeroBce")
                        .IsUnique()
                        .HasDatabaseName("ix_affilie_numero_bce")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("affilie", (string)null);
                });

            modelBuilder.Entity("Sepp.Affilies.Domain.Affilies.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<string>("Fonction")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("fonction");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nom");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("role");

                    b.Property<string>("Telephone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("telephone");

                    b.Property<Guid>("affilie_id")
                        .HasColumnType("uuid")
                        .HasColumnName("affilie_id");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset>("updated_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("updated_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.Property<int>("version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Validite", "Sepp.Affilies.Domain.Affilies.Contact.Validite#Validity", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateOnly>("ValidFrom")
                                .HasColumnType("date")
                                .HasColumnName("valid_from");

                            b1.Property<DateOnly?>("ValidTo")
                                .HasColumnType("date")
                                .HasColumnName("valid_to");
                        });

                    b.HasKey("Id")
                        .HasName("pk_contact");

                    b.HasIndex("affilie_id")
                        .HasDatabaseName("ix_contact_affilie_id");

                    b.ToTable("contact", (string)null);
                });

            modelBuilder.Entity("Sepp.Affilies.Domain.Affilies.Departement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nom");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<Guid>("site_id")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<DateTimeOffset>("updated_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("updated_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.Property<int>("version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Validite", "Sepp.Affilies.Domain.Affilies.Departement.Validite#Validity", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateOnly>("ValidFrom")
                                .HasColumnType("date")
                                .HasColumnName("valid_from");

                            b1.Property<DateOnly?>("ValidTo")
                                .HasColumnType("date")
                                .HasColumnName("valid_to");
                        });

                    b.HasKey("Id")
                        .HasName("pk_departement");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_departement_parent_id");

                    b.HasIndex("site_id")
                        .HasDatabaseName("ix_departement_site_id");

                    b.ToTable("departement", (string)null);
                });

            modelBuilder.Entity("Sepp.Affilies.Domain.Affilies.OperationAffilie", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AffilieAbsorbantId")
                        .HasColumnType("uuid")
                        .HasColumnName("affilie_absorbant_id");

                    b.PrimitiveCollection<Guid[]>("AffiliesBeneficiaires")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("affilies_beneficiaires");

                    b.Property<DateOnly>("DateEffet")
                        .HasColumnType("date")
                        .HasColumnName("date_effet");

                    b.Property<DateOnly?>("DateRealisation")
                        .HasColumnType("date")
                        .HasColumnName("date_realisation");

                    b.Property<string>("SeppContrepartie")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("sepp_contrepartie");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("statut");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type");

                    b.Property<Guid>("affilie_id")
                        .HasColumnType("uuid")
                        .HasColumnName("affilie_id");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset>("updated_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("updated_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.Property<int>("version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_operation_affilie");

                    b.HasIndex("AffilieAbsorbantId")
                        .HasDatabaseName("ix_operation_affilie_affilie_absorbant_id");

                    b.HasIndex("affilie_id")
                        .HasDatabaseName("ix_operation_affilie_affilie_id");

                    b.ToTable("operation_affilie", (string)null);
                });

            modelBuilder.Entity("Sepp.Affilies.Domain.Affilies.OrganeConcertation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type");

                    b.Property<Guid>("affilie_id")
                        .HasColumnType("uuid")
                        .HasColumnName("affilie_id");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset>("updated_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("updated_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.Property<int>("version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Validite", "Sepp.Affilies.Domain.Affilies.OrganeConcertation.Validite#Validity", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateOnly>("ValidFrom")
                                .HasColumnType("date")
                                .HasColumnName("valid_from");

                            b1.Property<DateOnly?>("ValidTo")
                                .HasColumnType("date")
                                .HasColumnName("valid_to");
                        });

                    b.HasKey("Id")
                        .HasName("pk_organe_concertation");

                    b.HasIndex("affilie_id")
                        .HasDatabaseName("ix_organe_concertation_affilie_id");

                    b.ToTable("organe_concertation", (string)null);
                });

            modelBuilder.Entity("Sepp.Affilies.Domain.Affilies.ReunionConcertation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("DateReunion")
                        .HasColumnType("date")
                        .HasColumnName("date_reunion");

                    b.Property<Guid?>("OrdreDuJourDocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<bool>("ParticipationSepp")
                        .HasColumnType("boolean")
                        .HasColumnName("participation_sepp");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<Guid>("organe_concertation_id")
                        .HasColumnType("uuid")
                        .HasColumnName("organe_concertation_id");

                    b.Property<DateTimeOffset>("updated_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("updated_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.Property<int>("version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_reunion_concertation");

                    b.HasIndex("organe_concertation_id")
                        .HasDatabaseName("ix_reunion_concertation_organe_concertation_id");

                    b.ToTable("reunion_concertation", (string)null);
                });

            modelBuilder.Entity("Sepp.Affilies.Domain.Affilies.Site", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nom");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<Guid>("unite_etablissement_id")
                        .HasColumnType("uuid")
                        .HasColumnName("unite_etablissement_id");

                    b.Property<DateTimeOffset>("updated_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("updated_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.Property<int>("version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Adresse", "Sepp.Affilies.Domain.Affilies.Site.Adresse#Adresse", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Boite")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("adresse_boite");

                            b1.Property<string>("CodePays")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)")
                                .HasColumnName("adresse_code_pays");

                            b1.Property<string>("CodePostal")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("adresse_code_postal");

                            b1.Property<string>("Localite")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("adresse_localite");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("adresse_numero");

                            b1.Property<string>("Rue")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("adresse_rue");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Validite", "Sepp.Affilies.Domain.Affilies.Site.Validite#Validity", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateOnly>("ValidFrom")
                                .HasColumnType("date")
                                .HasColumnName("valid_from");

                            b1.Property<DateOnly?>("ValidTo")
                                .HasColumnType("date")
                                .HasColumnName("valid_to");
                        });

                    b.HasKey("Id")
                        .HasName("pk_site");

                    b.HasIndex("unite_etablissement_id")
                        .HasDatabaseName("ix_site_unite_etablissement_id");

                    b.ToTable("site", (string)null);
                });

            modelBuilder.Entity("Sepp.Affilies.Domain.Affilies.UniteEtablissement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Langue")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("langue");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nom");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("numero_ue_bce");

                    b.Property<Guid>("affilie_id")
                        .HasColumnType("uuid")
                        .HasColumnName("affilie_id");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset>("updated_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("updated_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.Property<int>("version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Adresse", "Sepp.Affilies.Domain.Affilies.UniteEtablissement.Adresse#Adresse", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Boite")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("adresse_boite");

                            b1.Property<string>("CodePays")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)")
                                .HasColumnName("adresse_code_pays");

                            b1.Property<string>("CodePostal")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("adresse_code_postal");

                            b1.Property<string>("Localite")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("adresse_localite");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("adresse_numero");

                            b1.Property<string>("Rue")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("adresse_rue");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Validite", "Sepp.Affilies.Domain.Affilies.UniteEtablissement.Validite#Validity", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateOnly>("ValidFrom")
                                .HasColumnType("date")
                                .HasColumnName("valid_from");

                            b1.Property<DateOnly?>("ValidTo")
                                .HasColumnType("date")
                                .HasColumnName("valid_to");
                        });

                    b.HasKey("Id")
                        .HasName("pk_unite_etablissement");

                    b.HasIndex("Numero")
                        .IsUnique()
                        .HasDatabaseName("ix_unite_etablissement_numero_ue_bce");

                    b.HasIndex("affilie_id")
                        .HasDatabaseName("ix_unite_etablissement_affilie_id");

                    b.ToTable("unite_etablissement", (string)null);
                });

            modelBuilder.Entity("Sepp.Affilies.Domain.Groupes.Groupe", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nom");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("deleted_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTimeOffset>("updated_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("updated_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.Property<int>("version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_groupe");

                    b.ToTable("groupe", (string)null);
                });

            modelBuilder.Entity("Sepp.Affilies.Domain.Historique.ModificationAffilie", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action");

                    b.Property<Guid>("AffilieId")
                        .HasColumnType("uuid")
                        .HasColumnName("affilie_id");

                    b.Property<string>("Apres")
                        .HasColumnType("jsonb")
                        .HasColumnName("apres");

                    b.Property<string>("Auteur")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("auteur");

                    b.Property<string>("Avant")
                        .HasColumnType("jsonb")
                        .HasColumnName("avant");

                    b.Property<DateTimeOffset>("Horodatage")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("horodatage");

                    b.Property<int>("NumeroVersion")
                        .HasColumnType("integer")
                        .HasColumnName("numero_version");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset>("updated_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("updated_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.Property<int>("version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_modification_affilie");

                    b.HasIndex("AffilieId", "NumeroVersion")
                        .IsUnique()
                        .HasDatabaseName("ix_modification_affilie_affilie_id_numero_version");

                    b.ToTable("modification_affilie", (string)null);
                });

            modelBuilder.Entity("Sepp.BuildingBlocks.Infrastructure.Messaging.InboxMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<string>("Consumer")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("consumer");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.HasKey("MessageId", "Consumer")
                        .HasName("pk_inbox_message");

                    b.ToTable("inbox_message", (string)null);
                });

            modelBuilder.Entity("Sepp.BuildingBlocks.Infrastructure.Messaging.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("event_type");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("topic");

                    b.HasKey("Id")
                        .HasName("pk_outbox_message");

                    b.HasIndex("ProcessedAt")
                        .HasDatabaseName("ix_outbox_message_processed_at")
                        .HasFilter("processed_at IS NULL");

                    b.ToTable("outbox_message", (string)null);
                });

            modelBuilder.Entity("Sepp.Affilies.Domain.Affilies.Affilie", b =>
                {
                    b.HasOne("Sepp.Affilies.Domain.Groupes.Groupe", null)
                        .WithMany()
                        .HasForeignKey("GroupeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_affilie_groupe_groupe_id");
                });

            modelBuilder.Entity("Sepp.Affilies.Domain.Affilies.Contact", b =>
                {
                    b.HasOne("Sepp.Affilies.Domain.Affilies.Affilie", null)
                        .WithMany("Contacts")
                        .HasForeignKey("affilie_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_contact_affilie_affilie_id");
                });

            modelBuilder.Entity("Sepp.Affilies.Domain.Affilies.Departement", b =>
                {
                    b.HasOne("Sepp.Affilies.Domain.Affilies.Departement", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_departement_departement_parent_id");

                    b.HasOne("Sepp.Affilies.Domain.Affilies.Site", null)
                        .WithMany("Departements")
                        .HasForeignKey("site_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_departement_site_site_id");
                });

            modelBuilder.Entity("Sepp.Affilies.Domain.Affilies.OperationAffilie", b =>
                {
                    b.HasOne("Sepp.Affilies.Domain.Affilies.Affilie", null)
                        .WithMany("Operations")
                        .HasForeignKey("affilie_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_operation_affilie_affilie_affilie_id");
                });

            modelBuilder.Entity("Sepp.Affilies.Domain.Affilies.OrganeConcertation", b =>
                {
                    b.HasOne("Sepp.Affilies.Domain.Affilies.Affilie", null)
                        .WithMany("OrganesConcertation")
                        .HasForeignKey("affilie_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_organe_concertation_affilie_affilie_id");
                });

            modelBuilder.Entity("Sepp.Affilies.Domain.Affilies.ReunionConcertation", b =>
                {
                    b.HasOne("Sepp.Affilies.Domain.Affilies.OrganeConcertation", null)
                        .WithMany("Reunions")
                        .HasForeignKey("organe_concertation_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reunion_concertation_organe_concertation_organe_concertatio");
                });

            modelBuilder.Entity("Sepp.Affilies.Domain.Affilies.Site", b =>
                {
                    b.HasOne("Sepp.Affilies.Domain.Affilies.UniteEtablissement", null)
                        .WithMany("Sites")
                        .HasForeignKey("unite_etablissement_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_site_unite_etablissement_unite_etablissement_id");
                });

            modelBuilder.Entity("Sepp.Affilies.Domain.Affilies.UniteEtablissement", b =>
                {
                    b.HasOne("Sepp.Affilies.Domain.Affilies.Affilie", null)
                        .WithMany("UnitesEtablissement")
                        .HasForeignKey("affilie_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_unite_etablissement_affilie_affilie_id");
                });

            modelBuilder.Entity("Sepp.Affilies.Domain.Historique.ModificationAffilie", b =>
                {
                    b.HasOne("Sepp.Affilies.Domain.Affilies.Affilie", null)
                        .WithMany()
                        .HasForeignKey("AffilieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_modification_affilie_affilie_affilie_id");
                });

            modelBuilder.Entity("Sepp.Affilies.Domain.Affilies.Affilie", b =>
                {
                    b.Navigation("Contacts");

                    b.Navigation("Operations");

                    b.Navigation("OrganesConcertation");

                    b.Navigation("UnitesEtablissement");
                });

            modelBuilder.Entity("Sepp.Affilies.Domain.Affilies.OrganeConcertation", b =>
                {
                    b.Navigation("Reunions");
                });

            modelBuilder.Entity("Sepp.Affilies.Domain.Affilies.Site", b =>
                {
                    b.Navigation("Departements");
                });

            modelBuilder.Entity("Sepp.Affilies.Domain.Affilies.UniteEtablissement", b =>
                {
                    b.Navigation("Sites");
                });
#pragma warning restore 612, 618
        }
    }
}
