<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <AssemblyName>Sepp.PostesRisques</AssemblyName>
    <RootNamespace>Sepp.PostesRisques.Infrastructure</RootNamespace>
    <UserSecretsId>sepp-postes-risques</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" PrivateAssets="all" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Sepp.PostesRisques.Adapters\Sepp.PostesRisques.Adapters.csproj" />
  </ItemGroup>
</Project>
