// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sepp.Planification.Adapters.Persistence;

#nullable disable

namespace Sepp.Planification.Adapters.Persistence.Migrations
{
    [DbContext(typeof(PlanificationDbContext))]
    [Migration("20261005134310_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sepp.BuildingBlocks.Infrastructure.Messaging.InboxMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<string>("Consumer")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("consumer");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.HasKey("MessageId", "Consumer")
                        .HasName("pk_inbox_message");

                    b.ToTable("inbox_message", (string)null);
                });

            modelBuilder.Entity("Sepp.BuildingBlocks.Infrastructure.Messaging.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("event_type");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("topic");

                    b.HasKey("Id")
                        .HasName("pk_outbox_message");

                    b.HasIndex("ProcessedAt")
                        .HasDatabaseName("ix_outbox_message_processed_at")
                        .HasFilter("processed_at IS NULL");

                    b.ToTable("outbox_message", (string)null);
                });

            modelBuilder.Entity("Sepp.Planification.Domain.Agenda.Creneau", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("Debut")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("debut");

                    b.Property<DateTimeOffset>("Fin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fin");

                    b.Property<Guid>("LieuId")
                        .HasColumnType("uuid")
                        .HasColumnName("lieu_id");

                    b.Property<Guid?>("ModeleAgendaId")
                        .HasColumnType("uuid")
                        .HasColumnName("modele_agenda_id");

                    b.Property<bool>("OuvertEnLigne")
                        .HasColumnType("boolean")
                        .HasColumnName("ouvert_en_ligne");

                    b.Property<bool>("ReserveUrgence")
                        .HasColumnType("boolean")
                        .HasColumnName("reserve_urgence");

                    b.Property<Guid>("RessourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("ressource_id");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("statut");

                    b.Property<string>("TypeActe")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type_acte");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("deleted_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTimeOffset>("updated_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("updated_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.Property<int>("version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_creneau");

                    b.HasIndex("LieuId")
                        .HasDatabaseName("ix_creneau_lieu_id");

                    b.HasIndex("ModeleAgendaId")
                        .HasDatabaseName("ix_creneau_modele_agenda_id");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_creneau_session_id");

                    b.HasIndex("RessourceId", "Debut")
                        .HasDatabaseName("ix_creneau_ressource_id_debut");

                    b.HasIndex("Statut", "Debut")
                        .HasDatabaseName("ix_creneau_statut_debut");

                    b.ToTable("creneau", (string)null);
                });

            modelBuilder.Entity("Sepp.Planification.Domain.Agenda.DureeStandard", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("DureeMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duree_minutes");

                    b.Property<Guid?>("RessourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("ressource_id");

                    b.Property<string>("TypeActe")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type_acte");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("deleted_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTimeOffset>("updated_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("updated_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.Property<int>("version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_duree_standard");

                    b.HasIndex("RessourceId")
                        .HasDatabaseName("ix_duree_standard_ressource_id");

                    b.HasIndex("TypeActe")
                        .IsUnique()
                        .HasDatabaseName("ux_duree_standard_globale")
                        .HasFilter("ressource_id IS NULL");

                    b.HasIndex("TypeActe", "RessourceId")
                        .IsUnique()
                        .HasDatabaseName("ux_duree_standard_ressource")
                        .HasFilter("ressource_id IS NOT NULL");

                    b.ToTable("duree_standard", (string)null);
                });

            modelBuilder.Entity("Sepp.Planification.Domain.Agenda.ModeleAgenda", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("LieuId")
                        .HasColumnType("uuid")
                        .HasColumnName("lieu_id");

                    b.Property<Guid>("RessourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("ressource_id");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("deleted_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTimeOffset>("updated_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("updated_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.Property<int>("version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Validite", "Sepp.Planification.Domain.Agenda.ModeleAgenda.Validite#Validity", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateOnly>("ValidFrom")
                                .HasColumnType("date")
                                .HasColumnName("valid_from");

                            b1.Property<DateOnly?>("ValidTo")
                                .HasColumnType("date")
                                .HasColumnName("valid_to");
                        });

                    b.HasKey("Id")
                        .HasName("pk_modele_agenda");

                    b.HasIndex("LieuId")
                        .HasDatabaseName("ix_modele_agenda_lieu_id");

                    b.HasIndex("RessourceId")
                        .HasDatabaseName("ix_modele_agenda_ressource_id");

                    b.ToTable("modele_agenda", (string)null);
                });

            modelBuilder.Entity("Sepp.Planification.Domain.Agenda.OccupationRessource", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("Debut")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("debut");

                    b.Property<DateTimeOffset>("Fin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fin");

                    b.Property<Guid>("RessourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("ressource_id");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<Guid>("creneau_id")
                        .HasColumnType("uuid")
                        .HasColumnName("creneau_id");

                    b.Property<DateTimeOffset>("updated_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("updated_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.Property<int>("version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_occupation_ressource");

                    b.HasIndex("creneau_id")
                        .HasDatabaseName("ix_occupation_ressource_creneau_id");

                    b.HasIndex("RessourceId", "Debut")
                        .HasDatabaseName("ix_occupation_ressource_ressource_id_debut");

                    b.ToTable("occupation_ressource", (string)null);
                });

            modelBuilder.Entity("Sepp.Planification.Domain.Agenda.PlageModele", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<TimeOnly>("Debut")
                        .HasColumnType("time without time zone")
                        .HasColumnName("debut");

                    b.Property<int>("DureeMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duree_minutes");

                    b.Property<TimeOnly>("Fin")
                        .HasColumnType("time without time zone")
                        .HasColumnName("fin");

                    b.Property<string>("Jour")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("jour");

                    b.Property<bool>("OuvertEnLigne")
                        .HasColumnType("boolean")
                        .HasColumnName("ouvert_en_ligne");

                    b.Property<bool>("ReserveUrgence")
                        .HasColumnType("boolean")
                        .HasColumnName("reserve_urgence");

                    b.PrimitiveCollection<Guid[]>("RessourcesAssociees")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("ressources_associees");

                    b.Property<string>("TypeActe")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type_acte");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<Guid>("modele_agenda_id")
                        .HasColumnType("uuid")
                        .HasColumnName("modele_agenda_id");

                    b.Property<DateTimeOffset>("updated_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("updated_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.Property<int>("version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_plage_modele");

                    b.HasIndex("modele_agenda_id")
                        .HasDatabaseName("ix_plage_modele_modele_agenda_id");

                    b.ToTable("plage_modele", (string)null);
                });

            modelBuilder.Entity("Sepp.Planification.Domain.Agenda.RendezVous", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AffilieId")
                        .HasColumnType("uuid")
                        .HasColumnName("affilie_id");

                    b.Property<DateTimeOffset?>("AppeleA")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("appele_a");

                    b.Property<DateTimeOffset?>("ArriveeA")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("arrivee_a");

                    b.Property<Guid>("CreneauId")
                        .HasColumnType("uuid")
                        .HasColumnName("creneau_id");

                    b.Property<DateTimeOffset>("Debut")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("debut");

                    b.Property<DateTimeOffset>("Fin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fin");

                    b.Property<Guid>("LieuId")
                        .HasColumnType("uuid")
                        .HasColumnName("lieu_id");

                    b.Property<string>("MotifAnnulation")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("motif_annulation");

                    b.PrimitiveCollection<Guid[]>("ObligationIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("obligation_ids");

                    b.Property<string>("Origine")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("origine");

                    b.Property<Guid>("PersonneId")
                        .HasColumnType("uuid")
                        .HasColumnName("personne_id");

                    b.Property<DateTimeOffset>("PlanifieLe")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("planifie_le");

                    b.Property<DateTimeOffset?>("Rappel1EmisLe")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rappel1emis_le");

                    b.Property<DateTimeOffset?>("Rappel2EmisLe")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rappel2emis_le");

                    b.Property<Guid?>("ReconvocationDeId")
                        .HasColumnType("uuid")
                        .HasColumnName("reconvocation_de_id");

                    b.Property<string>("ReferenceAgendaExterne")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("reference_agenda_externe");

                    b.Property<Guid>("RessourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("ressource_id");

                    b.Property<Guid?>("SalleId")
                        .HasColumnType("uuid")
                        .HasColumnName("salle_id");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("statut");

                    b.Property<string>("TypeActe")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type_acte");

                    b.Property<bool>("Urgent")
                        .HasColumnType("boolean")
                        .HasColumnName("urgent");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("deleted_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTimeOffset>("updated_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("updated_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.Property<int>("version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_rendez_vous");

                    b.HasIndex("CreneauId")
                        .IsUnique()
                        .HasDatabaseName("ux_rendez_vous_creneau_actif")
                        .HasFilter("statut IN ('Planifie', 'Arrive', 'EnSalle')");

                    b.HasIndex("AffilieId", "Debut")
                        .HasDatabaseName("ix_rendez_vous_affilie_id_debut");

                    b.HasIndex("LieuId", "Debut")
                        .HasDatabaseName("ix_rendez_vous_lieu_id_debut");

                    b.HasIndex("PersonneId", "Debut")
                        .HasDatabaseName("ix_rendez_vous_personne_id_debut");

                    b.HasIndex("RessourceId", "Debut")
                        .HasDatabaseName("ix_rendez_vous_ressource_id_debut");

                    b.ToTable("rendez_vous", (string)null);
                });

            modelBuilder.Entity("Sepp.Planification.Domain.Convocations.Convocation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AffilieId")
                        .HasColumnType("uuid")
                        .HasColumnName("affilie_id");

                    b.Property<string>("Canal")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("canal");

                    b.Property<DateTimeOffset>("DateEmission")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_emission");

                    b.Property<DateTimeOffset?>("DateEnvoi")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_envoi");

                    b.Property<Guid?>("LotId")
                        .HasColumnType("uuid")
                        .HasColumnName("lot_id");

                    b.Property<string>("MessageId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("message_id");

                    b.Property<Guid>("PersonneId")
                        .HasColumnType("uuid")
                        .HasColumnName("personne_id");

                    b.Property<bool>("Recommande")
                        .HasColumnType("boolean")
                        .HasColumnName("recommande");

                    b.Property<Guid>("RendezVousId")
                        .HasColumnType("uuid")
                        .HasColumnName("rendez_vous_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("deleted_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTimeOffset>("updated_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("updated_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.Property<int>("version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_convocation");

                    b.HasIndex("LotId")
                        .HasDatabaseName("ix_convocation_lot_id");

                    b.HasIndex("RendezVousId")
                        .HasDatabaseName("ix_convocation_rendez_vous_id");

                    b.ToTable("convocation", (string)null);
                });

            modelBuilder.Entity("Sepp.Planification.Domain.Convocations.PreferenceConvocation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AffilieId")
                        .HasColumnType("uuid")
                        .HasColumnName("affilie_id");

                    b.Property<string>("Canal")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("canal");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("deleted_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTimeOffset>("updated_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("updated_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.Property<int>("version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_preference_convocation");

                    b.HasIndex("AffilieId")
                        .IsUnique()
                        .HasDatabaseName("ix_preference_convocation_affilie_id");

                    b.ToTable("preference_convocation", (string)null);
                });

            modelBuilder.Entity("Sepp.Planification.Domain.Projections.ObligationAPlanifier", b =>
                {
                    b.Property<Guid>("ObligationId")
                        .HasColumnType("uuid")
                        .HasColumnName("obligation_id");

                    b.Property<Guid>("AffilieId")
                        .HasColumnType("uuid")
                        .HasColumnName("affilie_id");

                    b.Property<DateOnly>("DateDue")
                        .HasColumnType("date")
                        .HasColumnName("date_due");

                    b.Property<DateOnly?>("DateLimite")
                        .HasColumnType("date")
                        .HasColumnName("date_limite");

                    b.Property<bool>("Echue")
                        .HasColumnType("boolean")
                        .HasColumnName("echue");

                    b.Property<DateTimeOffset>("EvenementDu")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("evenement_du");

                    b.Property<Guid>("PersonneId")
                        .HasColumnType("uuid")
                        .HasColumnName("personne_id");

                    b.Property<Guid?>("RendezVousId")
                        .HasColumnType("uuid")
                        .HasColumnName("rendez_vous_id");

                    b.Property<string>("TypeExamen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("type_examen");

                    b.Property<bool>("UrgenceNonCouverte")
                        .HasColumnType("boolean")
                        .HasColumnName("urgence_non_couverte");

                    b.HasKey("ObligationId")
                        .HasName("pk_obligation_a_planifier");

                    b.HasIndex("PersonneId")
                        .HasDatabaseName("ix_obligation_a_planifier_personne_id");

                    b.HasIndex("RendezVousId")
                        .HasDatabaseName("ix_obligation_a_planifier_rendez_vous_id");

                    b.HasIndex("AffilieId", "DateDue")
                        .HasDatabaseName("ix_obligation_a_planifier_affilie_id_date_due");

                    b.ToTable("obligation_a_planifier", (string)null);
                });

            modelBuilder.Entity("Sepp.Planification.Domain.Projections.ParametreLegalLocal", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<DateOnly>("ValideDu")
                        .HasColumnType("date")
                        .HasColumnName("valide_du");

                    b.Property<string>("Unite")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("unite");

                    b.Property<decimal>("Valeur")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("valeur");

                    b.Property<DateOnly?>("ValideJusquAu")
                        .HasColumnType("date")
                        .HasColumnName("valide_jusqu_au");

                    b.HasKey("Code", "ValideDu")
                        .HasName("pk_parametre_legal_local");

                    b.ToTable("parametre_legal_local", (string)null);
                });

            modelBuilder.Entity("Sepp.Planification.Domain.Ressources.Absence", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("Debut")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("debut");

                    b.Property<DateTimeOffset>("Fin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fin");

                    b.Property<string>("ReferenceExterne")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("reference_externe");

                    b.Property<Guid>("RessourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("ressource_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("source");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("deleted_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTimeOffset>("updated_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("updated_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.Property<int>("version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_absence");

                    b.HasIndex("RessourceId", "Debut")
                        .HasDatabaseName("ix_absence_ressource_id_debut");

                    b.HasIndex("Source", "ReferenceExterne")
                        .IsUnique()
                        .HasDatabaseName("ix_absence_source_reference_externe")
                        .HasFilter("reference_externe IS NOT NULL");

                    b.ToTable("absence", (string)null);
                });

            modelBuilder.Entity("Sepp.Planification.Domain.Ressources.Lieu", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Actif")
                        .HasColumnType("boolean")
                        .HasColumnName("actif");

                    b.Property<string>("Adresse")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("adresse");

                    b.Property<Guid?>("AffilieId")
                        .HasColumnType("uuid")
                        .HasColumnName("affilie_id");

                    b.Property<string>("CodePostal")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("code_postal");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nom");

                    b.Property<Guid?>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("deleted_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTimeOffset>("updated_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("updated_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.Property<int>("version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_lieu");

                    b.HasIndex("AffilieId")
                        .HasDatabaseName("ix_lieu_affilie_id");

                    b.ToTable("lieu", (string)null);
                });

            modelBuilder.Entity("Sepp.Planification.Domain.Ressources.Ressource", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.PrimitiveCollection<string[]>("Competences")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("competences");

                    b.Property<string>("CompteAgenda")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("compte_agenda");

                    b.Property<string>("FournisseurAgenda")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("fournisseur_agenda");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("libelle");

                    b.Property<Guid?>("LieuId")
                        .HasColumnType("uuid")
                        .HasColumnName("lieu_id");

                    b.Property<string>("ReferenceId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reference_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("deleted_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTimeOffset>("updated_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("updated_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.Property<int>("version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_ressource");

                    b.HasIndex("LieuId")
                        .HasDatabaseName("ix_ressource_lieu_id");

                    b.HasIndex("ReferenceId")
                        .HasDatabaseName("ix_ressource_reference_id");

                    b.ToTable("ressource", (string)null);
                });

            modelBuilder.Entity("Sepp.Planification.Domain.Sessions.EtapeTournee", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Emplacement")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("emplacement");

                    b.Property<TimeOnly?>("HeureArrivee")
                        .HasColumnType("time without time zone")
                        .HasColumnName("heure_arrivee");

                    b.Property<int>("Ordre")
                        .HasColumnType("integer")
                        .HasColumnName("ordre");

                    b.Property<bool>("RaccordementEau")
                        .HasColumnType("boolean")
                        .HasColumnName("raccordement_eau");

                    b.Property<bool>("RaccordementElectrique")
                        .HasColumnType("boolean")
                        .HasColumnName("raccordement_electrique");

                    b.Property<bool>("RaccordementReseau")
                        .HasColumnType("boolean")
                        .HasColumnName("raccordement_reseau");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<Guid>("session_id")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<DateTimeOffset>("updated_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("updated_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.Property<int>("version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_etape_tournee");

                    b.HasIndex("session_id")
                        .HasDatabaseName("ix_etape_tournee_session_id");

                    b.ToTable("etape_tournee", (string)null);
                });

            modelBuilder.Entity("Sepp.Planification.Domain.Sessions.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AffilieId")
                        .HasColumnType("uuid")
                        .HasColumnName("affilie_id");

                    b.Property<int>("CapaciteJournaliere")
                        .HasColumnType("integer")
                        .HasColumnName("capacite_journaliere");

                    b.Property<Guid?>("ChauffeurId")
                        .HasColumnType("uuid")
                        .HasColumnName("chauffeur_id");

                    b.Property<Guid>("ConseillerId")
                        .HasColumnType("uuid")
                        .HasColumnName("conseiller_id");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<int>("DureeMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duree_minutes");

                    b.Property<TimeOnly>("HeureDebut")
                        .HasColumnType("time without time zone")
                        .HasColumnName("heure_debut");

                    b.Property<Guid>("LieuId")
                        .HasColumnType("uuid")
                        .HasColumnName("lieu_id");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("statut");

                    b.Property<string>("TypeActe")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type_acte");

                    b.Property<Guid?>("UniteMobileId")
                        .HasColumnType("uuid")
                        .HasColumnName("unite_mobile_id");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("deleted_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTimeOffset>("updated_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("updated_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.Property<int>("version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_session");

                    b.HasIndex("ConseillerId")
                        .HasDatabaseName("ix_session_conseiller_id");

                    b.HasIndex("Date")
                        .HasDatabaseName("ix_session_date");

                    b.HasIndex("LieuId")
                        .HasDatabaseName("ix_session_lieu_id");

                    b.ToTable("session", (string)null);
                });

            modelBuilder.Entity("Sepp.Planification.Domain.Agenda.Creneau", b =>
                {
                    b.HasOne("Sepp.Planification.Domain.Ressources.Lieu", null)
                        .WithMany()
                        .HasForeignKey("LieuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_creneau_lieu_lieu_id");

                    b.HasOne("Sepp.Planification.Domain.Agenda.ModeleAgenda", null)
                        .WithMany()
                        .HasForeignKey("ModeleAgendaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_creneau_modele_agenda_modele_agenda_id");

                    b.HasOne("Sepp.Planification.Domain.Ressources.Ressource", null)
                        .WithMany()
                        .HasForeignKey("RessourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_creneau_ressource_ressource_id");

                    b.HasOne("Sepp.Planification.Domain.Sessions.Session", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_creneau_sessions_session_id");
                });

            modelBuilder.Entity("Sepp.Planification.Domain.Agenda.DureeStandard", b =>
                {
                    b.HasOne("Sepp.Planification.Domain.Ressources.Ressource", null)
                        .WithMany()
                        .HasForeignKey("RessourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_duree_standard_ressource_ressource_id");
                });

            modelBuilder.Entity("Sepp.Planification.Domain.Agenda.ModeleAgenda", b =>
                {
                    b.HasOne("Sepp.Planification.Domain.Ressources.Lieu", null)
                        .WithMany()
                        .HasForeignKey("LieuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_modele_agenda_lieu_lieu_id");

                    b.HasOne("Sepp.Planification.Domain.Ressources.Ressource", null)
                        .WithMany()
                        .HasForeignKey("RessourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_modele_agenda_ressource_ressource_id");
                });

            modelBuilder.Entity("Sepp.Planification.Domain.Agenda.OccupationRessource", b =>
                {
                    b.HasOne("Sepp.Planification.Domain.Ressources.Ressource", null)
                        .WithMany()
                        .HasForeignKey("RessourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_occupation_ressource_ressource_ressource_id");

                    b.HasOne("Sepp.Planification.Domain.Agenda.Creneau", null)
                        .WithMany("Occupations")
                        .HasForeignKey("creneau_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_occupation_ressource_creneau_creneau_id");
                });

            modelBuilder.Entity("Sepp.Planification.Domain.Agenda.PlageModele", b =>
                {
                    b.HasOne("Sepp.Planification.Domain.Agenda.ModeleAgenda", null)
                        .WithMany("Plages")
                        .HasForeignKey("modele_agenda_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_plage_modele_modele_agenda_modele_agenda_id");
                });

            modelBuilder.Entity("Sepp.Planification.Domain.Agenda.RendezVous", b =>
                {
                    b.HasOne("Sepp.Planification.Domain.Agenda.Creneau", null)
                        .WithMany()
                        .HasForeignKey("CreneauId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_rendez_vous_creneau_creneau_id");
                });

            modelBuilder.Entity("Sepp.Planification.Domain.Convocations.Convocation", b =>
                {
                    b.HasOne("Sepp.Planification.Domain.Agenda.RendezVous", null)
                        .WithMany()
                        .HasForeignKey("RendezVousId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_convocation_rendez_vous_rendez_vous_id");
                });

            modelBuilder.Entity("Sepp.Planification.Domain.Ressources.Absence", b =>
                {
                    b.HasOne("Sepp.Planification.Domain.Ressources.Ressource", null)
                        .WithMany()
                        .HasForeignKey("RessourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_absence_ressource_ressource_id");
                });

            modelBuilder.Entity("Sepp.Planification.Domain.Ressources.Ressource", b =>
                {
                    b.HasOne("Sepp.Planification.Domain.Ressources.Lieu", null)
                        .WithMany()
                        .HasForeignKey("LieuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_ressource_lieu_lieu_id");
                });

            modelBuilder.Entity("Sepp.Planification.Domain.Sessions.EtapeTournee", b =>
                {
                    b.HasOne("Sepp.Planification.Domain.Sessions.Session", null)
                        .WithMany("Itineraire")
                        .HasForeignKey("session_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_etape_tournee_session_session_id");
                });

            modelBuilder.Entity("Sepp.Planification.Domain.Sessions.Session", b =>
                {
                    b.HasOne("Sepp.Planification.Domain.Ressources.Ressource", null)
                        .WithMany()
                        .HasForeignKey("ConseillerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_session_ressource_conseiller_id");

                    b.HasOne("Sepp.Planification.Domain.Ressources.Lieu", null)
                        .WithMany()
                        .HasForeignKey("LieuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_session_lieu_lieu_id");
                });

            modelBuilder.Entity("Sepp.Planification.Domain.Agenda.Creneau", b =>
                {
                    b.Navigation("Occupations");
                });

            modelBuilder.Entity("Sepp.Planification.Domain.Agenda.ModeleAgenda", b =>
                {
                    b.Navigation("Plages");
                });

            modelBuilder.Entity("Sepp.Planification.Domain.Sessions.Session", b =>
                {
                    b.Navigation("Itineraire");
                });
#pragma warning restore 612, 618
        }
    }
}
