// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sepp.Referentiels.Adapters.Persistence;

#nullable disable

namespace Sepp.Referentiels.Adapters.Persistence.Migrations
{
    [DbContext(typeof(ReferentielsDbContext))]
    [Migration("20260928074255_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sepp.BuildingBlocks.Infrastructure.Messaging.InboxMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<string>("Consumer")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("consumer");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.HasKey("MessageId", "Consumer")
                        .HasName("pk_inbox_message");

                    b.ToTable("inbox_message", (string)null);
                });

            modelBuilder.Entity("Sepp.BuildingBlocks.Infrastructure.Messaging.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("event_type");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("topic");

                    b.HasKey("Id")
                        .HasName("pk_outbox_message");

                    b.HasIndex("ProcessedAt")
                        .HasDatabaseName("ix_outbox_message_processed_at")
                        .HasFilter("processed_at IS NULL");

                    b.ToTable("outbox_message", (string)null);
                });

            modelBuilder.Entity("Sepp.Referentiels.Domain.Calendrier.CalendrierAnnuel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Annee")
                        .HasColumnType("integer")
                        .HasColumnName("annee");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("deleted_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTimeOffset>("updated_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("updated_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.Property<int>("version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_calendrier_annuel");

                    b.HasIndex("Annee")
                        .IsUnique()
                        .HasDatabaseName("ix_calendrier_annuel_annee");

                    b.ToTable("calendrier_annuel", (string)null);
                });

            modelBuilder.Entity("Sepp.Referentiels.Domain.Calendrier.JourFerieSupplementaire", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<Guid>("calendrier_annuel_id")
                        .HasColumnType("uuid")
                        .HasColumnName("calendrier_annuel_id");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset>("updated_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("updated_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.Property<int>("version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Libelle", "Sepp.Referentiels.Domain.Calendrier.JourFerieSupplementaire.Libelle#LocalizedLabel", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("De")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("libelle_de");

                            b1.Property<string>("En")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("libelle_en");

                            b1.Property<string>("Fr")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("libelle_fr");

                            b1.Property<string>("Nl")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("libelle_nl");
                        });

                    b.HasKey("Id")
                        .HasName("pk_jour_ferie_supplementaire");

                    b.HasIndex("calendrier_annuel_id")
                        .HasDatabaseName("ix_jour_ferie_supplementaire_calendrier_annuel_id");

                    b.ToTable("jour_ferie_supplementaire", (string)null);
                });

            modelBuilder.Entity("Sepp.Referentiels.Domain.Nomenclatures.EntreeNomenclature", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<string>("CodeParent")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code_parent");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<Guid>("nomenclature_id")
                        .HasColumnType("uuid")
                        .HasColumnName("nomenclature_id");

                    b.Property<DateTimeOffset>("updated_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("updated_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.Property<int>("version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Libelle", "Sepp.Referentiels.Domain.Nomenclatures.EntreeNomenclature.Libelle#LocalizedLabel", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("De")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("libelle_de");

                            b1.Property<string>("En")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("libelle_en");

                            b1.Property<string>("Fr")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("libelle_fr");

                            b1.Property<string>("Nl")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("libelle_nl");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Validite", "Sepp.Referentiels.Domain.Nomenclatures.EntreeNomenclature.Validite#Validity", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateOnly>("ValidFrom")
                                .HasColumnType("date")
                                .HasColumnName("valid_from");

                            b1.Property<DateOnly?>("ValidTo")
                                .HasColumnType("date")
                                .HasColumnName("valid_to");
                        });

                    b.HasKey("Id")
                        .HasName("pk_entree_nomenclature");

                    b.HasIndex("nomenclature_id", "Code")
                        .HasDatabaseName("ix_entree_nomenclature_nomenclature_id_code");

                    b.ToTable("entree_nomenclature", (string)null);
                });

            modelBuilder.Entity("Sepp.Referentiels.Domain.Nomenclatures.Nomenclature", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<int>("NumeroVersion")
                        .HasColumnType("integer")
                        .HasColumnName("numero_version");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("deleted_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTimeOffset>("updated_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("updated_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.Property<int>("version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Libelle", "Sepp.Referentiels.Domain.Nomenclatures.Nomenclature.Libelle#LocalizedLabel", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("De")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("libelle_de");

                            b1.Property<string>("En")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("libelle_en");

                            b1.Property<string>("Fr")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("libelle_fr");

                            b1.Property<string>("Nl")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("libelle_nl");
                        });

                    b.HasKey("Id")
                        .HasName("pk_nomenclature");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_nomenclature_code");

                    b.ToTable("nomenclature", (string)null);
                });

            modelBuilder.Entity("Sepp.Referentiels.Domain.Parametres.ParametreLegal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BaseLegale")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("base_legale");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<string>("Unite")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("unite");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("deleted_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTimeOffset>("updated_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("updated_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.Property<int>("version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Libelle", "Sepp.Referentiels.Domain.Parametres.ParametreLegal.Libelle#LocalizedLabel", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("De")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("libelle_de");

                            b1.Property<string>("En")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("libelle_en");

                            b1.Property<string>("Fr")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("libelle_fr");

                            b1.Property<string>("Nl")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("libelle_nl");
                        });

                    b.HasKey("Id")
                        .HasName("pk_parametre_legal");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_parametre_legal_code");

                    b.ToTable("parametre_legal", (string)null);
                });

            modelBuilder.Entity("Sepp.Referentiels.Domain.Parametres.ValeurParametre", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Valeur")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("valeur");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<Guid>("parametre_legal_id")
                        .HasColumnType("uuid")
                        .HasColumnName("parametre_legal_id");

                    b.Property<DateTimeOffset>("updated_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("updated_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.Property<int>("version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Validite", "Sepp.Referentiels.Domain.Parametres.ValeurParametre.Validite#Validity", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateOnly>("ValidFrom")
                                .HasColumnType("date")
                                .HasColumnName("valid_from");

                            b1.Property<DateOnly?>("ValidTo")
                                .HasColumnType("date")
                                .HasColumnName("valid_to");
                        });

                    b.HasKey("Id")
                        .HasName("pk_valeur_parametre");

                    b.HasIndex("parametre_legal_id")
                        .HasDatabaseName("ix_valeur_parametre_parametre_legal_id");

                    b.ToTable("valeur_parametre", (string)null);
                });

            modelBuilder.Entity("Sepp.Referentiels.Domain.Calendrier.JourFerieSupplementaire", b =>
                {
                    b.HasOne("Sepp.Referentiels.Domain.Calendrier.CalendrierAnnuel", null)
                        .WithMany("JoursSupplementaires")
                        .HasForeignKey("calendrier_annuel_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_jour_ferie_supplementaire_calendrier_annuel_calendrier_annu");
                });

            modelBuilder.Entity("Sepp.Referentiels.Domain.Nomenclatures.EntreeNomenclature", b =>
                {
                    b.HasOne("Sepp.Referentiels.Domain.Nomenclatures.Nomenclature", null)
                        .WithMany("Entrees")
                        .HasForeignKey("nomenclature_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_entree_nomenclature_nomenclature_nomenclature_id");
                });

            modelBuilder.Entity("Sepp.Referentiels.Domain.Parametres.ValeurParametre", b =>
                {
                    b.HasOne("Sepp.Referentiels.Domain.Parametres.ParametreLegal", null)
                        .WithMany("Valeurs")
                        .HasForeignKey("parametre_legal_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_valeur_parametre_parametre_legal_parametre_legal_id");
                });

            modelBuilder.Entity("Sepp.Referentiels.Domain.Calendrier.CalendrierAnnuel", b =>
                {
                    b.Navigation("JoursSupplementaires");
                });

            modelBuilder.Entity("Sepp.Referentiels.Domain.Nomenclatures.Nomenclature", b =>
                {
                    b.Navigation("Entrees");
                });

            modelBuilder.Entity("Sepp.Referentiels.Domain.Parametres.ParametreLegal", b =>
                {
                    b.Navigation("Valeurs");
                });
#pragma warning restore 612, 618
        }
    }
}
