// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sepp.Obligations.Adapters.Persistence;

#nullable disable

namespace Sepp.Obligations.Adapters.Persistence.Migrations
{
    [DbContext(typeof(ObligationsDbContext))]
    [Migration("20261005140035_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sepp.BuildingBlocks.Infrastructure.Messaging.InboxMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<string>("Consumer")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("consumer");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.HasKey("MessageId", "Consumer")
                        .HasName("pk_inbox_message");

                    b.ToTable("inbox_message", (string)null);
                });

            modelBuilder.Entity("Sepp.BuildingBlocks.Infrastructure.Messaging.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("event_type");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("topic");

                    b.HasKey("Id")
                        .HasName("pk_outbox_message");

                    b.HasIndex("ProcessedAt")
                        .HasDatabaseName("ix_outbox_message_processed_at")
                        .HasFilter("processed_at IS NULL");

                    b.ToTable("outbox_message", (string)null);
                });

            modelBuilder.Entity("Sepp.Obligations.Domain.Demandes.DemandeTravailleur", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AffilieId")
                        .HasColumnType("uuid")
                        .HasColumnName("affilie_id");

                    b.Property<DateOnly>("DateDemande")
                        .HasColumnType("date")
                        .HasColumnName("date_demande");

                    b.Property<string>("EnregistreePar")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("enregistree_par");

                    b.Property<Guid>("PersonneId")
                        .HasColumnType("uuid")
                        .HasColumnName("personne_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("deleted_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTimeOffset>("updated_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("updated_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.Property<int>("version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_demande_travailleur");

                    b.HasIndex("PersonneId")
                        .HasDatabaseName("ix_demande_travailleur_personne_id");

                    b.ToTable("demande_travailleur", (string)null);
                });

            modelBuilder.Entity("Sepp.Obligations.Domain.Obligations.Obligation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AffilieId")
                        .HasColumnType("uuid")
                        .HasColumnName("affilie_id");

                    b.Property<string>("Cle")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("cle");

                    b.PrimitiveCollection<string[]>("CodesRisques")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("codes_risques");

                    b.Property<DateOnly>("DateDue")
                        .HasColumnType("date")
                        .HasColumnName("date_due");

                    b.Property<DateOnly?>("DateLimite")
                        .HasColumnType("date")
                        .HasColumnName("date_limite");

                    b.Property<DateOnly?>("DateRealisation")
                        .HasColumnType("date")
                        .HasColumnName("date_realisation");

                    b.Property<DateTimeOffset?>("DateRendezVous")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_rendez_vous");

                    b.Property<DateOnly?>("DateReport")
                        .HasColumnType("date")
                        .HasColumnName("date_report");

                    b.Property<DateOnly?>("EchueSignaleeLe")
                        .HasColumnType("date")
                        .HasColumnName("echue_signalee_le");

                    b.Property<Guid?>("ExamenId")
                        .HasColumnType("uuid")
                        .HasColumnName("examen_id");

                    b.Property<string>("MotifAnnulation")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("motif_annulation");

                    b.Property<string>("Origine")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("origine");

                    b.Property<Guid>("PersonneId")
                        .HasColumnType("uuid")
                        .HasColumnName("personne_id");

                    b.Property<Guid?>("RendezVousId")
                        .HasColumnType("uuid")
                        .HasColumnName("rendez_vous_id");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("statut");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("deleted_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTimeOffset>("updated_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("updated_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.Property<int>("version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_obligation");

                    b.HasIndex("AffilieId", "Statut")
                        .HasDatabaseName("ix_obligation_affilie_id_statut");

                    b.HasIndex("PersonneId", "Cle")
                        .IsUnique()
                        .HasDatabaseName("ix_obligation_personne_id_cle");

                    b.ToTable("obligation", (string)null);
                });

            modelBuilder.Entity("Sepp.Obligations.Domain.Obligations.TraceCalcul", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("DateCalcul")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_calcul");

                    b.PrimitiveCollection<string[]>("Entrees")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("entrees");

                    b.Property<string>("Explication")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("explication");

                    b.Property<int>("Numero")
                        .HasColumnType("integer")
                        .HasColumnName("numero");

                    b.Property<string>("Regle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("regle");

                    b.Property<int?>("RegleVersion")
                        .HasColumnType("integer")
                        .HasColumnName("regle_version");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<Guid>("obligation_id")
                        .HasColumnType("uuid")
                        .HasColumnName("obligation_id");

                    b.Property<DateTimeOffset>("updated_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("updated_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.Property<int>("version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_trace_calcul");

                    b.HasIndex("obligation_id")
                        .HasDatabaseName("ix_trace_calcul_obligation_id");

                    b.ToTable("trace_calcul", (string)null);
                });

            modelBuilder.Entity("Sepp.Obligations.Domain.Projections.AffectationLocale", b =>
                {
                    b.Property<Guid>("AffectationId")
                        .HasColumnType("uuid")
                        .HasColumnName("affectation_id");

                    b.Property<DateOnly>("DateDebut")
                        .HasColumnType("date")
                        .HasColumnName("date_debut");

                    b.Property<DateOnly?>("DateFin")
                        .HasColumnType("date")
                        .HasColumnName("date_fin");

                    b.Property<DateTimeOffset>("EvenementDu")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("evenement_du");

                    b.Property<Guid>("PersonneId")
                        .HasColumnType("uuid")
                        .HasColumnName("personne_id");

                    b.Property<Guid>("PosteId")
                        .HasColumnType("uuid")
                        .HasColumnName("poste_id");

                    b.HasKey("AffectationId")
                        .HasName("pk_affectation_locale");

                    b.HasIndex("PersonneId")
                        .HasDatabaseName("ix_affectation_locale_personne_id");

                    b.HasIndex("PosteId")
                        .HasDatabaseName("ix_affectation_locale_poste_id");

                    b.ToTable("affectation_locale", (string)null);
                });

            modelBuilder.Entity("Sepp.Obligations.Domain.Projections.CalendrierLocal", b =>
                {
                    b.Property<int>("Annee")
                        .HasColumnType("integer")
                        .HasColumnName("annee");

                    b.Property<DateTimeOffset>("EvenementDu")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("evenement_du");

                    b.PrimitiveCollection<DateOnly[]>("JoursSupplementaires")
                        .IsRequired()
                        .HasColumnType("date[]")
                        .HasColumnName("jours_supplementaires");

                    b.HasKey("Annee")
                        .HasName("pk_calendrier_local");

                    b.ToTable("calendrier_local", (string)null);
                });

            modelBuilder.Entity("Sepp.Obligations.Domain.Projections.EtatParticulierLocal", b =>
                {
                    b.Property<Guid>("EtatParticulierId")
                        .HasColumnType("uuid")
                        .HasColumnName("etat_particulier_id");

                    b.Property<string>("Categorie")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("categorie");

                    b.Property<DateOnly>("DateDebut")
                        .HasColumnType("date")
                        .HasColumnName("date_debut");

                    b.Property<DateOnly?>("DateFin")
                        .HasColumnType("date")
                        .HasColumnName("date_fin");

                    b.Property<DateTimeOffset>("EvenementDu")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("evenement_du");

                    b.Property<Guid>("PersonneId")
                        .HasColumnType("uuid")
                        .HasColumnName("personne_id");

                    b.HasKey("EtatParticulierId")
                        .HasName("pk_etat_particulier_local");

                    b.HasIndex("PersonneId")
                        .HasDatabaseName("ix_etat_particulier_local_personne_id");

                    b.ToTable("etat_particulier_local", (string)null);
                });

            modelBuilder.Entity("Sepp.Obligations.Domain.Projections.ExamenLocal", b =>
                {
                    b.Property<Guid>("ExamenId")
                        .HasColumnType("uuid")
                        .HasColumnName("examen_id");

                    b.Property<Guid>("AffilieId")
                        .HasColumnType("uuid")
                        .HasColumnName("affilie_id");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<Guid>("PersonneId")
                        .HasColumnType("uuid")
                        .HasColumnName("personne_id");

                    b.Property<string>("TypeExamen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("type_examen");

                    b.HasKey("ExamenId")
                        .HasName("pk_examen_local");

                    b.HasIndex("PersonneId")
                        .HasDatabaseName("ix_examen_local_personne_id");

                    b.ToTable("examen_local", (string)null);
                });

            modelBuilder.Entity("Sepp.Obligations.Domain.Projections.IncapaciteLocale", b =>
                {
                    b.Property<Guid>("IncapaciteId")
                        .HasColumnType("uuid")
                        .HasColumnName("incapacite_id");

                    b.Property<Guid>("AffilieId")
                        .HasColumnType("uuid")
                        .HasColumnName("affilie_id");

                    b.Property<DateOnly>("DateDebut")
                        .HasColumnType("date")
                        .HasColumnName("date_debut");

                    b.Property<Guid>("PersonneId")
                        .HasColumnType("uuid")
                        .HasColumnName("personne_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("source");

                    b.HasKey("IncapaciteId")
                        .HasName("pk_incapacite_locale");

                    b.HasIndex("PersonneId")
                        .HasDatabaseName("ix_incapacite_locale_personne_id");

                    b.ToTable("incapacite_locale", (string)null);
                });

            modelBuilder.Entity("Sepp.Obligations.Domain.Projections.ListeNominativeLocale", b =>
                {
                    b.Property<Guid>("ListeNominativeId")
                        .HasColumnType("uuid")
                        .HasColumnName("liste_nominative_id");

                    b.Property<Guid>("AffilieId")
                        .HasColumnType("uuid")
                        .HasColumnName("affilie_id");

                    b.Property<DateOnly>("DateGeneration")
                        .HasColumnType("date")
                        .HasColumnName("date_generation");

                    b.Property<DateOnly>("DateReference")
                        .HasColumnType("date")
                        .HasColumnName("date_reference");

                    b.Property<string>("TypeListe")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("type_liste");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("ListeNominativeId")
                        .HasName("pk_liste_nominative_locale");

                    b.HasIndex("AffilieId")
                        .HasDatabaseName("ix_liste_nominative_locale_affilie_id");

                    b.ToTable("liste_nominative_locale", (string)null);
                });

            modelBuilder.Entity("Sepp.Obligations.Domain.Projections.OccupationLocale", b =>
                {
                    b.Property<Guid>("OccupationId")
                        .HasColumnType("uuid")
                        .HasColumnName("occupation_id");

                    b.Property<Guid>("AffilieId")
                        .HasColumnType("uuid")
                        .HasColumnName("affilie_id");

                    b.Property<DateOnly?>("DateDebut")
                        .HasColumnType("date")
                        .HasColumnName("date_debut");

                    b.Property<DateOnly?>("DateFin")
                        .HasColumnType("date")
                        .HasColumnName("date_fin");

                    b.Property<DateTimeOffset?>("FinRecueDu")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fin_recue_du");

                    b.Property<Guid>("PersonneId")
                        .HasColumnType("uuid")
                        .HasColumnName("personne_id");

                    b.HasKey("OccupationId")
                        .HasName("pk_occupation_locale");

                    b.HasIndex("AffilieId")
                        .HasDatabaseName("ix_occupation_locale_affilie_id");

                    b.HasIndex("PersonneId")
                        .HasDatabaseName("ix_occupation_locale_personne_id");

                    b.ToTable("occupation_locale", (string)null);
                });

            modelBuilder.Entity("Sepp.Obligations.Domain.Projections.ParametreLegalLocal", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<DateOnly>("ValideDu")
                        .HasColumnType("date")
                        .HasColumnName("valide_du");

                    b.Property<DateTimeOffset>("EvenementDu")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("evenement_du");

                    b.Property<string>("Unite")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("unite");

                    b.Property<decimal>("Valeur")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("valeur");

                    b.Property<DateOnly?>("ValideJusquAu")
                        .HasColumnType("date")
                        .HasColumnName("valide_jusqu_au");

                    b.HasKey("Code", "ValideDu")
                        .HasName("pk_parametre_legal_local");

                    b.ToTable("parametre_legal_local", (string)null);
                });

            modelBuilder.Entity("Sepp.Obligations.Domain.Projections.ProfilRisquePosteLocal", b =>
                {
                    b.Property<Guid>("PosteId")
                        .HasColumnType("uuid")
                        .HasColumnName("poste_id");

                    b.Property<DateOnly>("ValideDu")
                        .HasColumnType("date")
                        .HasColumnName("valide_du");

                    b.Property<Guid>("AffilieId")
                        .HasColumnType("uuid")
                        .HasColumnName("affilie_id");

                    b.PrimitiveCollection<string[]>("CodesRisques")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("codes_risques");

                    b.Property<DateTimeOffset>("EvenementDu")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("evenement_du");

                    b.HasKey("PosteId", "ValideDu")
                        .HasName("pk_profil_risque_poste_local");

                    b.ToTable("profil_risque_poste_local", (string)null);
                });

            modelBuilder.Entity("Sepp.Obligations.Domain.Projections.RegleSurveillanceLocale", b =>
                {
                    b.Property<string>("CodeRisque")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code_risque");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<string>("Categorie")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("categorie");

                    b.Property<int?>("FrequenceMois")
                        .HasColumnType("integer")
                        .HasColumnName("frequence_mois");

                    b.Property<Guid>("RisqueId")
                        .HasColumnType("uuid")
                        .HasColumnName("risque_id");

                    b.Property<bool>("SurveillanceProlongee")
                        .HasColumnType("boolean")
                        .HasColumnName("surveillance_prolongee");

                    b.Property<string>("TypeSurveillance")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("type_surveillance");

                    b.Property<DateOnly>("ValideDu")
                        .HasColumnType("date")
                        .HasColumnName("valide_du");

                    b.HasKey("CodeRisque", "Version")
                        .HasName("pk_regle_surveillance_locale");

                    b.ToTable("regle_surveillance_locale", (string)null);
                });

            modelBuilder.Entity("Sepp.Obligations.Domain.Projections.RendezVousLocal", b =>
                {
                    b.Property<Guid>("RendezVousId")
                        .HasColumnType("uuid")
                        .HasColumnName("rendez_vous_id");

                    b.Property<Guid?>("AffilieId")
                        .HasColumnType("uuid")
                        .HasColumnName("affilie_id");

                    b.Property<bool>("Annule")
                        .HasColumnType("boolean")
                        .HasColumnName("annule");

                    b.Property<DateTimeOffset?>("Debut")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("debut");

                    b.PrimitiveCollection<Guid[]>("ObligationIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("obligation_ids");

                    b.Property<Guid>("PersonneId")
                        .HasColumnType("uuid")
                        .HasColumnName("personne_id");

                    b.Property<DateTimeOffset?>("PlanifieDu")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("planifie_du");

                    b.HasKey("RendezVousId")
                        .HasName("pk_rendez_vous_local");

                    b.HasIndex("PersonneId")
                        .HasDatabaseName("ix_rendez_vous_local_personne_id");

                    b.ToTable("rendez_vous_local", (string)null);
                });

            modelBuilder.Entity("Sepp.Obligations.Domain.Projections.RepriseLocale", b =>
                {
                    b.Property<Guid>("PersonneId")
                        .HasColumnType("uuid")
                        .HasColumnName("personne_id");

                    b.Property<Guid>("AffilieId")
                        .HasColumnType("uuid")
                        .HasColumnName("affilie_id");

                    b.Property<DateOnly>("DateReprise")
                        .HasColumnType("date")
                        .HasColumnName("date_reprise");

                    b.Property<DateOnly>("DebutAbsence")
                        .HasColumnType("date")
                        .HasColumnName("debut_absence");

                    b.Property<DateTimeOffset>("EvenementDu")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("evenement_du");

                    b.HasKey("PersonneId", "AffilieId", "DateReprise")
                        .HasName("pk_reprise_locale");

                    b.ToTable("reprise_locale", (string)null);
                });

            modelBuilder.Entity("Sepp.Obligations.Domain.Projections.SurchargeFrequenceLocale", b =>
                {
                    b.Property<Guid>("SurchargeId")
                        .HasColumnType("uuid")
                        .HasColumnName("surcharge_id");

                    b.Property<Guid>("AffilieId")
                        .HasColumnType("uuid")
                        .HasColumnName("affilie_id");

                    b.Property<Guid>("CibleId")
                        .HasColumnType("uuid")
                        .HasColumnName("cible_id");

                    b.Property<string>("CibleType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("cible_type");

                    b.Property<string>("CodeRisque")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code_risque");

                    b.Property<DateTimeOffset>("EvenementDu")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("evenement_du");

                    b.Property<int>("FrequenceMois")
                        .HasColumnType("integer")
                        .HasColumnName("frequence_mois");

                    b.Property<DateOnly>("ValideDu")
                        .HasColumnType("date")
                        .HasColumnName("valide_du");

                    b.Property<DateOnly?>("ValideJusquAu")
                        .HasColumnType("date")
                        .HasColumnName("valide_jusqu_au");

                    b.HasKey("SurchargeId")
                        .HasName("pk_surcharge_frequence_locale");

                    b.HasIndex("CibleId")
                        .HasDatabaseName("ix_surcharge_frequence_locale_cible_id");

                    b.ToTable("surcharge_frequence_locale", (string)null);
                });

            modelBuilder.Entity("Sepp.Obligations.Domain.Projections.TrajetLocal", b =>
                {
                    b.Property<Guid>("TrajetId")
                        .HasColumnType("uuid")
                        .HasColumnName("trajet_id");

                    b.Property<Guid>("AffilieId")
                        .HasColumnType("uuid")
                        .HasColumnName("affilie_id");

                    b.Property<DateOnly?>("DateDemande")
                        .HasColumnType("date")
                        .HasColumnName("date_demande");

                    b.Property<DateOnly?>("DateFin")
                        .HasColumnType("date")
                        .HasColumnName("date_fin");

                    b.Property<Guid>("PersonneId")
                        .HasColumnType("uuid")
                        .HasColumnName("personne_id");

                    b.Property<string>("Statut")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("statut");

                    b.HasKey("TrajetId")
                        .HasName("pk_trajet_local");

                    b.HasIndex("PersonneId")
                        .HasDatabaseName("ix_trajet_local_personne_id");

                    b.ToTable("trajet_local", (string)null);
                });

            modelBuilder.Entity("Sepp.Obligations.Domain.Obligations.TraceCalcul", b =>
                {
                    b.HasOne("Sepp.Obligations.Domain.Obligations.Obligation", null)
                        .WithMany("Traces")
                        .HasForeignKey("obligation_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_trace_calcul_obligation_obligation_id");
                });

            modelBuilder.Entity("Sepp.Obligations.Domain.Obligations.Obligation", b =>
                {
                    b.Navigation("Traces");
                });
#pragma warning restore 612, 618
        }
    }
}
